### ISSUE TITLE
Integrating lightncandy with backend database

### ISSUE THREAD

**Issue by brunobg** [zordius/lightncandy#112]
I'd like to integrate lightncandy to automatically read data from a database backend. I'd like some tips as to the best way to do it, please -- not regarding the backend, of course, but the parsing. Here's the idea in more detail.

I'll have a template with tags that will be read from the DB, in the context of an object. For example, ```This is {{name}} of type {{type}}, associated with other items: {{#association}}{{name}} which is {{color}},{{/association}}``` will read `name` from the database, as an attribute of this object. `#association` will read a list of other objects, and render the subtemplate with their data.

Therefore my idea is something like this:

1. the names single tags should be accessible in an array, which will be used as keys to fetch from the database. In the example above, I want to get something like `['name', 'type']`. The tags should ideally be matched against the argument passed to render ($in); tags that do not have keys in $in are the ones that will be queried in the database. I'd like to get all tags in an array, because it will be much more efficient to fetch them from the database all at once than one at a time. 
2. sections can be used for associations between objects and therefore should be accessible too, but they'll get data from another context. In the example, I may have 3 other objects which will be queried for `['name', 'color']`. It's possible of course to have many levels of associations, recursively (`{{#association1}}...{{#association2}}...{{/association2}}...{{/association1}}`), and I need to separate the tags by level. Since associations are dynamic I'll have to hit the database again for each level, which is why this separation would be useful.

In the end will have an API like this:

```
class MyObject {
    public function render($template, $in) {
         // compiles template if not previously compiled and parse tags
         // fetch from database any single tags
         // recurse subtemplate for associations/sections (or alternatively just fetch data recursively and store into the template arguments)
         // actually render the template with fetched data plus $in
    }
} 
```

I've implemented this before with another mustache parser by extending the parser itself, but lightncandy seems to be more flexible and perhaps there is a way to do it more easily. Even if there is not, some general pointers as to how extend the code for this would be greatly appreciated.

I'd like to avoid something like `{{fetch name}}` because it's not practical at all cost. 

Thanks in advance for any suggestions!

**Comment by zordius** [comment]
Hello~ did these tips help? I close this now, but welcome to highlight any other questions by creating new issues, thanks.

**Comment by brunobg** [comment]
Hi Zordius, I haven't been able to test it yet, but I got your idea now. I am not sure it will work that easily, because I'm not using the full path "meta.gender". In multiple {{#loops}} it may require something else to work, I think. 

It's not a solution that I like very much, because it would require to build the NamedObj and access it with __get(), which is considerably slower than the patch I proposed.

**Comment by zordius** [comment]
Ya I think this may need more inputs. To keep 'the original parsed names' or 'the orignal tags' somehow overlap with 'template debug' feature.....even more, maybe we can build something like 'sourceMap in javascript' to hint more for helpers or developers.

When thinking in this way, provide 'only parsed variable names' maybe not best solution. I will keep thinking on these issues, and thank you for your inputs again!

**Comment by zordius** [comment]
Here is another thinking about `#ifatt` : because this helper is special case for your TreeCandy and you can totally handle it, how about to change the interface of it from {{#ifatt varname "compare"}} to {{#ifatt "varname" "compare"}} ???

* need to change #ifatt inside logic, get variable value by input name from $options (but now you can not get current scope from $options, this is a missing piece)
* this only handle simple "varname" case well, but not good for "path.varname" case

how do you think? (I need to go to dump handlebars options to check is there any scope object kept inside then I can make LightnCandy to support this)

**Comment by brunobg** [comment]
Oh, a more general system would be very welcome! If I can help with that in anyway please let me know. Perhaps some object that kept the same information that is available at compile time? You already have it parsed and structured. Sourcemaps are probably an overkill IMHO. 

This could be controlled by a flag, and people who don't need it wouldn't have a performance loss. Even when you receive it, it's just data in an array, so the performance loss will be negligible. I'd be very happy if you had a new idea to solve this :)

Regarding your second proposal: yes, it would work. I don't need "path.varname" anywhere. It's only bit more cumbersome to use and it's not a general solution. On the other hand that patch I sent you worked very well for what we needed and it's in production already, so I wouldn't mind waiting for a more permanent solution.

**Comment by zordius** [comment]
Update: new lightncandy version v0.89 there is a new options FLAG_STRINGPARAMS which follows handlebars.js stringParams compile time option. With it, the custom helpers will receive param names but not values. And then, you can use `$options['_this'][$param]` to lookup the value (in javascript it can be done by `this[param]`). The handlebars.js example is here: https://github.com/wycats/handlebars.js/blob/9365b8290070f34bf797c836aed4335ce6a4094f/spec/string-params.js
