### ISSUE TITLE
Subexpression did not work porperly in some situations

### ISSUE THREAD

**Issue by ZengYiming** [zordius/lightncandy#124]
Hello:

I have two custom helper:
$var1 = true
$var2 = false
{{Class "abc" "efg" highlight=var1 yellow=var2}}  =>   class="abc efg highlight"

$var1 = 'a'
$var2 = 'b'
{{Equal var1 var2}} => false

but it not work when I use Equal helper as subexpression in the Class helper
$var1 = 'a'
$var2 = 'a'
{{Class hightlight=(Equal var1 var2)}}
unless I wrap the subexpression up in [ ], it will work fine. like this
{{Class hightlight=[(Equal var1 var2)]}}
this syntax is not compatible with handlebars.js

I also find subexpression works fine in custom block helper but not in default block helper
 like {{#if (Equal var1 var2)}}  or {{#unless (Equal var1 var2)}}

**Comment by zordius** [comment]
Added an example jsfiddle here: http://jsfiddle.net/wxLc79he/1/ ,  later will test on lightncandy with same template.

**Comment by zordius** [comment]
Current master should fixed this bug, please try again. Thank you for reporting this bug!

**Comment by ZengYiming** [comment]
Thank you !
But it still have two bugs at following situations:
* subexpression in subexpression
* subexpression in block helper(default helper, like "if" "unless")
I add some test in <http://jsfiddle.net/wxLc79he/2/>, these test work fine with handlebars, but failed with lightncandy

**Comment by zordius** [comment]
Thank you for your bug report and example, I will deal with this issue later.

**Comment by zordius** [comment]
Sorry, maybe I missed one bug (subexpression in subexpression) . I will add another test to check it.

**Comment by zordius** [comment]
It's lucky that `subexpression in subexpression` also be fixed.

jsfiddle: http://jsfiddle.net/wxLc79he/3/
lightncandy test: https://github.com/zordius/lightncandy/commit/aeeafe6a4d93fe438c3466d8d709ae1fa5aed211

Please try current master again, thanks.

**Comment by ZengYiming** [comment]
Thank you!
