### ISSUE TITLE
ParseTokenArgs method can not return the expected args when there is a space after ", ', (,etc.

### ISSUE THREAD

**Issue by ZengYiming** [zordius/lightncandy#125]
Hello:

I add some example at <http://jsfiddle.net/wxLc79he/5/>.These examples all failed with lightncandy. The all reasons are because there is a spase after `"`, `(`, `="`, `'`, `[`, `='`, `=(`

I found that the reason leads to these failures is about RegEx match in the function parseTockenArgs. It can not deal `" ok"` as I expected, because RegEx `/^"[^"]+$/` needs string has at least one non `"` character after `"`. And I tried to fix these bugs. I replace `+` with `*` at the seven RegEx, and add the following test case:

* `@expect array(false, array(array('( foo bar)'))) when input array(0,0,0,0,0,0,'( foo bar)'), array('flags' => array('advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0))`
* `@expect array(false, array(array('a'), array('" b c"'))) when input array(0,0,0,0,0,0,'a " b c"'), array('flags' => array('advar' => 1, 'this' => 1, 'namev' => 0, 'noesc' => 0))`
* `@expect array(false, array(array('a'), 'q' => array('" b c"'))) when input array(0,0,0,0,0,0,'a q=" b c"'), array('flags' => array('advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0))`
* `@expect array(false, array(array('foo'), array("' =='"), array('bar'))) when input array(0,0,0,0,0,0,"foo ' ==' bar"), array('flags' => array('advar' => 1, 'namev' => 1))`
* `@expect array(false, array(array('a'), array(' b c'))) when input array(0,0,0,0,0,0,'a [ b c]'), array('flags' => array('advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0))`
* `@expect array(false, array(array('a'), 'q' => array("' d e'"))) when input array(0,0,0,0,0,0,"a q=' d e'"), array('flags' => array('advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0))`
* `@expect array(false, array('q' => array('( foo bar)'))) when input array(0,0,0,0,0,0,'q=( foo bar)'), array('flags' => array('advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0))`

The result of phpunit has 3 failures. The fourth test case fail. And I can not get why it want to match the string begin with `\'` not the only `'`. One other failures is because `/="[^"]*$/` matchs `"==="`.

Sorry I have not enouph time to deal with this problem. 
I will be very grateful if you look at this issue!

**Comment by zordius** [comment]
Thank you for reporting these issues! I will check on these cases.

**Comment by zordius** [comment]
Now these issues should be fixed. I think the case `' =='` failed because LightnCandy will do single quote escape when `.compile()` and the unit test case should be `\' ==\'` . And I add more tests in https://github.com/zordius/lightncandy/commit/a3d49b4e69dba2f720b45c59599f1bf5ac9f9971 that more human readable. Thank you for your test cases!

**Comment by ZengYiming** [comment]
Thank you to fix these issues! But there is another bug. RegExp `/="[^"]*$/` can match both `foo=" abc"` and `"=="`. 

I have a custom block helper:

`{{#Compare foo "==" bar}}<div> YES </div>{{/Compare}}`  

When `/="[^"]*$/` find `"=="`, it expects a arg end with `"`.So the compiled result is not correct. 

`'=='` has the same error.

I also find test can not pass phpunit.

**Comment by zordius** [comment]
Just updated https://github.com/zordius/lightncandy/commit/4cb2c7e6ad8bd102106b3e0e23ed3648487af90d , please try again, thanks.
