### ISSUE TITLE
custom block helper does not create new scope

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#127]
Hi Zordius,

I found a problem about custom block helper. 

For a common #if helper, it will create a new scope, means:

```
data: ['name' => 'john', 'array' => [1,2,3]]

{{#each array}}
    {{#if true}}
         {{name}} #visiting current scope, ouput blank
         {{../name}} # visiting parent scope, output blank
         {{../../name}}  #up to root scope, output "john"
    {{/if}}
{{/each}}
```

It is fine!

But for a custom block helper with nothing pass for its options['fn']，it will not create a new scope.

```
data: ['name' => 'john', 'array' => [1,2,3]]

{{#each array}}
    {{#custom true}}
         {{name}} #visiting current scope, ouput blank
         {{../name}} # visiting parent scope, output "john"
    {{/custom}}
{{/each}}
```

However, it is not coordinate with handlebars, which always applies a new scope for a block helper. It means you have to use `{{../../name}}` to visit the properties in the second example with Handlebars.

How do you think of this problem? Do you think it worth to fix to make it coordinate with Handlebars? Since we may write some template code for both server and client side and this problem may stop this idea.

Thanks,
ssnau

**Comment by zordius** [comment]
I will check for lightncandy to ensure the scope change is correct or not. If it is not same with handlebars.js, I will fix this. Thank you for your reporting!

**Comment by zordius** [comment]
Created a jsfiddle to verify custom helper + scope behaviors: http://jsfiddle.net/oLz8vcdx/

**Comment by zordius** [comment]
confirmed as a bug, will fix it later.

**Comment by zordius** [comment]
Now this bug should be fixed, please try current master, thanks!

**Comment by ssnau** [comment]
Thank you very much! I will try with it.
