### ISSUE TITLE
../varname in root context

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#128]
test case:
```
data : ['name' => 'jack']

template:

{{../name}}

output:
jack
```

However, it should output nothing....

**Comment by zordius** [comment]
I will create a jsfiddle to verify this on handlebars.js first. Thank you for your reporting!

**Comment by zordius** [comment]
confirmed as a bug, will fix it later.
jsfiddle: http://jsfiddle.net/sqwoxym0/

**Comment by zordius** [comment]
It should be fixed now, please try current master, thanks.

**Comment by ssnau** [comment]
great!!
