### ISSUE TITLE
literal 0 is not traslated well

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#129]
JsFiddle: http://jsfiddle.net/0ds1whLh/

```
{{#if 0}}
   HELLO
{{else}}
   WORLD    
{{/if}}
```

LightnCandy output `WORLD` in such case. It looks LightnCandy treat number 0 as string "0"...

**Comment by zordius** [comment]
I will create a test to check the compiled template codes.

**Comment by zordius** [comment]
verified as a bug.

**TEMPLATE**
```
{{0}} , {{"OK"}} , {{true}}
```
**compiled code**
```
return ''.LCRun3::encq($cx, '0').' , '.LCRun3::encq($cx, 'OK').' , '.LCRun3::encq($cx, LCRun3::v($cx, $in, array('true'))).'';
```

**SHOULD BE**
```
return ''.LCRun3::encq($cx, 0).' , '.LCRun3::encq($cx, 'OK').' , '.LCRun3::encq($cx, LCRun3::v($cx, $in, array(true))).'';
```

**Comment by zordius** [comment]
after https://github.com/zordius/lightncandy/commit/7ae8289b7efdf424de48d37f56adb952c2d7ec84 this bug should be fixed. And now `{{0}} , {{"OK"}} , {{true}}` is compiled as this code:

```php
return ''.LCRun3::encq($cx, 0).' , '.LCRun3::encq($cx, 'OK').' , '.LCRun3::encq($cx, true).'';
```

Please try current master, thanks.
