### ISSUE TITLE
float 0 is true

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#130]
JSfiddle: http://jsfiddle.net/ce4avzc7/

```
data:
[
  "int0" => 0,
  "float0" => 0.0,
]

template:
{{#if int0}} int0 {{/if}}
{{#if float0}} float0 {{/if}}

output:
float0
```

Actually it should output nothing.

I think we should both check `int` and `float` in LightnCandy implementation since JS only provide `Number` type for handlebar.

**Comment by zordius** [comment]
this should depend on #129  and may behave well after #129 fixed.

**Comment by zordius** [comment]
updated jsfiddle here: http://jsfiddle.net/7pe7yanj/ (the original is not updated)

**Comment by zordius** [comment]
the original `{{#if}}` only knows 0 as false , now it also knows 0.0 as false. Please try current master, thanks.
