### ISSUE TITLE
LightnCandy cannot handle object with custom helper

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#132]
JS Fiddle: http://jsfiddle.net/qwxtv4u9/1/

When I register a custom helper named `object` to create object on demand, LightnCandy could not translate well and runtime error came out.

I find it always try to get the first item of any `PHP Array` in  `chret` function which is buggy. Then I try to change it as:

```
 public static function chret($ret, $op) {
       // add isset($ret[0])
        if (is_array($ret) && isset($ret[0])) {
            if (isset($ret[1]) && $ret[1]) {
                $op = $ret[1];
            }
            $ret = $ret[0];
        }

        switch ($op) {
            case 'enc':
                return htmlentities($ret, ENT_QUOTES, 'UTF-8');
            case 'encq':
                return preg_replace('/&#039;/', '&#x27;', htmlentities($ret, ENT_QUOTES, 'UTF-8'));
        }
        return $ret;
    }
``` 

It works well but I feel it look too tricky. Could you please have a look or to get a better way? Thanks!

**Comment by zordius** [comment]
Well, in most case a custom helper should return string for rendering (unless it always be used inside a sub expression) .

And I agree `chret` should be changed because we supports sub expression now.

**Comment by zordius** [comment]
I just figure out another way to handle this. If you wanna return an array in your helper, you can `return array($yourArray, 'asis')` . Is it good for you?

**Comment by ssnau** [comment]
Great! Add an `asis` flag is a very good idea. I think it will works for me.

**Comment by laurenhamel** [comment]
I see this thread has been closed for quite some time, but I recently encountered this very issue yet again, and trying to proposed solution of `return array($yourArray, 'asis')` has not yielded any success. Am I mistaken in believing that this was incorporated into the `1.2.3` release?
