### ISSUE TITLE
../varname in subexpression with each/if

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#134]
Fiddler: http://jsfiddle.net/t6h36mxg/3/

LightnCandy will generate an errored php file in such case. 
It looks that LightnCandy cannot figure out to use `ifv` rather than `ifvar`.
Would you please have a look? Thanks.

**Comment by zordius** [comment]
This bug is caused by internal features count error, not it is fixed. Please try current master, thank you for your reporting!
