### ISSUE TITLE
why check isset before is_array

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#136]
Hi Zordius,

I see the source code `getVariableName` will compile the variable name into something like: 

```
(isset($base$n) && is_array($base$p)) .....
```

But `isset` sometimes would throw error, for example:

```
class Person{ }
$person = new Person();
isset($person['name']); // throw error...
```

If we check `is_array` before `isset`, it looks safer in runtime. How do you think about their order?

Thanks

**Comment by zordius** [comment]
Your way is better, I will work on it later.

**Comment by zordius** [comment]
Well, after I did some modification, I run into problems of `{{../name}}` values and it is required to do another extra check on `isset($p)` . So this may cause some performance drop if I change

```php
(isset($base$n) && is_array($base$p))
```
to 
```php
(isset($base) && is_array($base$p) && isset($base$n))
```

Here is the new proposed way to do optimize:

1. when not tracking to parent:
   * + when not enable `FLAG_INSTANCE` : compile to `(isset($base$n) && is_array($base$p))`
   * + when enable `FLAG_INSTANCE` : compile to `(is_array($base$p) && isset($base$n))`
2. when tracking to parent:
   * + when not enable `FLAG_INSTANCE` : compile to `(isset($base$n) && is_array($base$p))`
   * + when enable `FLAG_INSTANCE` : compile to `(isset($base) && isset($base$n) && is_array($base$p))`

How do you think?

**Comment by zordius** [comment]
Hmmm...... maybe I missed something. When `FLAG_INSTANCE` enabled, all variable name will be compiled as `LCRun3::v(...)` but not faster array lookup syntax. So the question is: should we make the change to keep runtime safe from objects , and create another flag to highlight the performance drop? (Or just recommend people to use `FLAG_INSTANCE` when he like to pass objects into data?)

**Comment by ssnau** [comment]
Thanks for your investigation. If it only happens to objects, I think we can just choose the second way (recommend people to use `FLAG_INSTANCE`). It may be hard to avoid such error, since people may accidentally do such thing:

```
[
   "person" => [
       "name" => "jack",
       "profile" => new Profile()
   ]
]

and write template as {{ ../person.profile.location.street }}
```

it will run into error no matter we check `isset($base$p` or `is_array($base$p)`. It seems we don't have a good solution avoid runtime error unless ask people to enable `FLAG_INSTANCE`. I think it is OK for me to get runtime error under such situation.

**Comment by zordius** [comment]
this remind me to add some document about this.

**Comment by zordius** [comment]
https://github.com/zordius/lightncandy/commit/d2bfc97361e81ad50ebaecf5fd31a4bba6d6d199 doc about this.
