### ISSUE TITLE
服務器端 handlebars 与瀏覽器端 handlebars 的渲染區分

### ISSUE THREAD

**Issue by nimojs** [zordius/lightncandy#137]
還記得我之前所說的我們團隊在實踐的前端模擬後端模板引擎渲染麼？

我同事的後端框架已經開始使用 `lightncandy` ，我們前端的 `node` 開發工具也使用 `handlebars` 模擬數據編寫後端模板。

我遇到了一個問題：

`HTML` 的 `<script>` 中包含 `handlebars` 模板

```html
<script id="viewTpl1" type="text/x-handlebars-template">
{{#list}}
{{name}} * {{website}}
{{/list}}
</script>
```

因為node模擬服務器也是使用 `handlebars` 渲染頁面，導致最終頁面渲染結果是。

```html
<script id="viewTpl1" type="text/x-handlebars-template">
</script>
```
前端開發環境服務器與前端瀏覽器中使用的是完全相同的 `handlebars.js`，導致 `<script>` 中的模板被預先渲染。

我在開發環境做了簡單的調整：node 不渲染  `<script type="text/x-handlebars-template">...</script>`  中的內容，讓前端能通過 `type="text/x-handlebars-template"` 標識此script中的內容不在 node 中進行渲染。

請求 @zordius 考慮需不需要 `lightncandy` 中加入此功能。

附上前端代碼幫助表達我的需求：

[完整预览](http://jsbin.cn/rej/1/edit?html,js,console)

```javascript
// 关键代码
var oTplMap = {},
source = document.body.innerHTML;
source = source.replace(/<script.*?type=(["'])text\/x-handlebars-template\1>[\s\S]*?<\/script>/mg, function(){
    var sBrowserHandlebars = arguments[0],
    sReplaceFlag = new Date().getTime().toString()+Math.floor(Math.random(0,1)*1000000); // 1423129962742850219
    oTplMap[sReplaceFlag] = sBrowserHandlebars;
    return sReplaceFlag;
});
_.each(oTplMap, function(text,name, map){
    source = source.replace(new RegExp(name), '<!-- debug S -->' + text + '<!-- debug E -->');
});
document.body.innerHTML = source;
```

如果 `lightncandy` 中不應該加入此功能，希望 @zordius 能利用開發經驗指點出合適的解決方案。（在前後端都使用完全相同的 `handlebars.js` 時如果處理好渲染區分）

感謝！

**Comment by zordius** [comment]
Refer to #106 

想要避免render 某部份handlebars template , 可以利用 mustache 中原有的 "變換分界符號" 功能. 文件在這邊有: http://mustache.github.io/mustache.5.html 

例如: `{{=<% %>=}}` 的意思是把 `{{` 換成 `<%` , 把 `}}` 換成 `%>` . 之後再經過一次 `<%={{ }}=%>` , 就會換回來.

所以可以試著這樣寫: 

```html
<script id="viewTpl1" type="text/x-handlebars-template">{{=<% %>=}}
{{#list}}
{{name}} * {{website}}
{{/list}}
<%={{ }}=%></script>
```

另外一個小提醒.... handlebars.js 目前還不支援變換分界符號, 所以這個解法在nodejs + handlebars.js 中反而沒辦法用.

**Comment by zordius** [comment]
另外有個建議是, node 中應該用 precompile handlebars.js 的解法, performance 會比較好. 如果需要在client side 也作 rendering, 建議用別的方式把precompile 的template (會是js檔) 載進去. 當你們轉換成用這種方法後, 理論上也不會在html中看到 `<script id="viewTpl1" type="text/x-handlebars-template">`這種段落.

**Comment by nimojs** [comment]
感謝指點，我現在考慮 `<script>` 中的 `handlebars` 使用如下方式：
```html
<script type="text/x-handlebars-template">
<%#list%>
<%name%> * <%website%>
<%/list%>
</script>
```

js渲染时候 多一步 `replace(/<%/g,'{{').replace(/%>/g,'}}')` 转换。

`php`  `node`  `browser` handlebars 語法三個環境同時渲染真是一件有趣的事。

另外：`lightncandy` 可以提供變換分界符號功能麼？
```php
'tag_start' => '<%',
'tag_end' => '%>'
```
這樣我在編寫後端模板的時候就使用 <% name %> ，而前端的依然使用 `{{ name }}`。

**Comment by zordius** [comment]
我上面寫的code就是lightncandy可以跑的例子. 在node內你就利用你原本的regexp replace hack 去多處理 `{{=<% %>=}}` 及 `<%={{ }}=%>` 就可以了.

**Comment by nimojs** [comment]
哈...剛才有點沒反應過來，感谢！
