### ISSUE TITLE
Looping over array returned by subexpression {{#each (subExp "1234")}} does not work

### ISSUE THREAD

**Issue by madsleejensen** [zordius/lightncandy#138]
`{{#each}}` cant loop over a array returned by a sub-expression. (tested on: dev-master b97484f and ~0.19) 

```
<ul>
{{#each (mySubExpressionTest "1234")}}
    <li>{{this}}</li>
{{/each}}
</ul>
```

I have tested with: 

flags: `LightnCandy::FLAG_HANDLEBARSJS + LightnCandy::FLAG_ADVARNAME`
and 
flags: `LightnCandy::FLAG_HANDLEBARSJS`

The `mySubExpessionTest` simply returns a php `array("hello", "world")`

I have tested it with the javascript library which supports this behavior.

**Comment by zordius** [comment]
This is related with #132 , if you wanna implement a custom help to return array and it will be used inside a subexpression, you can `return array($myArray, 'asis')` . You can also get some info from document https://github.com/zordius/lightncandy#custom-helper-escaping .

**Comment by madsleejensen** [comment]
Thanks! That works :) But i noticed theres a problem with:
`{{#each (mySubExpressionTest "1234")}}` the `mySubExpressionTest` the sub expression is never called in context of {{#each}}. (works fine in {{#if}} {{#with}})

so this does not work:
```
<ul>
{{#each (mySubExpressionTest "1234")}}
    <li>{{this}}</li>
{{/each}}
</ul>
```

but this does: 
```
<ul>
{{#with (mySubExpressionTest "1234")}}
    {{#each this}}
        <li>{{this}}</li>
    {{/each}}
{{/with}}
</ul>
```

**Comment by zordius** [comment]
Now it should be fixed on current master, please try again. Thank you for reporting the bug!

**Comment by madsleejensen** [comment]
Just tested dev-master, works flawless :) thanks alot for your work on this library.
