### ISSUE TITLE
return false in custom block helper

### ISSUE THREAD

**Issue by ssnau** [zordius/lightncandy#139]
Hi Zordius,

Recently I run into a problem that our online machine constantly report error. However, the error does not contain any `stack information` which make me have no idea to locate where the problem is.

Finally I found there is an error log expression in `hbch`:

```
if ($r === false) {
            if ($e === null) {
                $e = "LCRun3: call custom helper '$ch' error";
            }
        }

        if($e !== null) {
            if ($cx['flags']['debug'] & self::DEBUG_ERROR_LOG) {
                error_log($e);
            }
            if ($cx['flags']['debug'] & self::DEBUG_ERROR_EXCEPTION) {
                throw new Exception($e);
            }
        }
```

That means I have returned a false in block helper, but why we have to stick to such logic? Since the `logic` and the `error msg` is a little obscure, do you think we can remove them?

Thanks

**Comment by zordius** [comment]
1. `$r` is result of `call_user_func_array` , based on PHP document ( http://php.net/manual/en/function.call-user-func-array.php ) it will be `false` when error. I think it's really an overlap with return value `false` from user function.
2. In the mean time I can not find a safe way to produce error when calling `call_user_func_array` . I know one way to produce `Missing argument n` error but it can not be try caught.

Maybe we can just remove the `$r === false` the make both 2 issues happy; but I do not feel 100% safe on this.

**Comment by ssnau** [comment]
Thank you!
