### ISSUE TITLE
Question about helpers

### ISSUE THREAD

**Issue by thrashy** [zordius/lightncandy#140]
I have many helpers that are organized into a class hierarchy. In my existing templates I have code like this:

{{helpers.user(context.activeUser, true).subscriber('online')}}

I know in the existing implementation you can use a space at the end of the instance method to specify arguments but what if you have multiple instance methods chained together with parameters along with nested method calls, which evaluate as part of the context and are not a custom helper?

What would be the best way to perform this in lightncandy?

Thanks in advance for any help!

**Comment by zordius** [comment]
1. I think the solution should be valid for both lightncandy and handlebars.js , so it is not a good solution to create a new syntax for this. Or, request new syntax for this at handlebars.js side, then lightncandy will follow up.
2. handlebars only cares about input data, put the context inside the input data is a good solution. EX: `render(array('context' => $Context), 'other_data' => ...))` (you may need to enable FLAG_INSTANCE)
3. you can use `[foo.bar]` to protect special characters inside your name including custom helper. EX: `{{[myNamespace.myHelperMethod] arg1 arg2}}` (you may need to enable FLAG_NAMEDARG if you do not enable FLAG_HANDLEBARS)
4. do not create complex custom helpers, it is not good when you want to share these templates with JavaScript or other languages. Test on both handlebars and lightncandy side when you using custom helpers to validate your new template and helpers.

**Comment by thrashy** [comment]
Thanks. That makes sense but we have 100's of existing templates using this functionality and want to add handlebars support. I think the conflicting syntax would cause too many issues so I might add an "eval" helper which would support the old helper syntax:

{{e "helpers.user(context.activeUser, true).subscriber('online')" @root}}

or leave it as is and add a pre-processor to the templates. It's more my problem than yours. :) Thanks for the help.

**Comment by zordius** [comment]
Yes, it's a good solution for your . Just be interested about your templates are migrated from which template engine? :)

**Comment by thrashy** [comment]
They're currently using a modified version of Mustache.php, which allows expression evaluation.
