### ISSUE TITLE
Passing parameters to partial

### ISSUE THREAD

**Issue by mrhanti** [zordius/lightncandy#142]
Besides the context argument. Is there any possible way to pass custom parameters to my partial

`{{> partialName context foo="bar"}}` ??

**Comment by stephenwf** [comment]
I believe FLAG_HANDLEBARS allows this.

**Comment by zordius** [comment]
Hmmm........... but , how another partial handle these extra parameters?

for example, this is a partial named as `foo`:
```
This is a partial dump context: {{.}}
```

this is the template:
```
I will include {{> foo . bar="123"}}
```

The included partial is not a custom helper, so it can not handle the parameter `bar` . Maybe we can handle your requirement by this way:

1. create a custom helper to merge parameters. EX: {{merge . foo="123" bar="456"}}
2. send new context into the partial. EX: {{>partial (merge . foo="123" bar="456")}}

Is this solution make sense?

**Comment by zordius** [comment]
closed for no follow up. Welcome to continue by more comments or create another issue, thanks.
