### ISSUE TITLE
Add compile flag to omit php opening and closing tags

### ISSUE THREAD

**Issue by kaldari** [zordius/lightncandy#144]
In MediaWiki we're using lightncandy in a slightly unorthodoxed way and would really like the ability to pass a compilation flag to LightnCandy::compile() that causes it to not generate the PHP tags that surround the code, i.e. "<?php" and "?>". In other words, have it compile to PHP code that could be directly evaled, rather than included.

**Comment by zordius** [comment]
seems good, I will work on it.

**Comment by zordius** [comment]
new FLAG_BARE created and now available on master, please try it, thanks.
