### ISSUE TITLE
{{this}} not working correctly in {{#each}} block?

### ISSUE THREAD

**Issue by iwilliams** [zordius/lightncandy#149]
It seems to me that `{{this}}` is not working as intended in an `{{#each}}` block. Take the following as an example:

This template:
```handlebars
{{#each scripts}}
  <script src="{{this}}"></script>
{{/each}}
```
being passed this array:

```php
array(
  "scripts" => array(
    "bower_components/jquery/dist/jquery.min.js",
    "bower_components/modernizr/modernizr.js",
    "bower_components/foundation/js/foundation.min.js"
  )
```
produces this html:
```html
<script src=""></script>
<script src=""></script>
<script src=""></script>
```

However, if I use this template:
```handlebars
{{#each scripts}}
  <script src="{{link}}"></script>
{{/each}}
```
with this array:
```php
array(
  "scripts" => array(
     array("link" => "bower_components/jquery/dist/jquery.min.js"),
     array("link" => "bower_components/modernizr/modernizr.js"),
     array("link" => "bower_components/foundation/js/foundation.min.js")
  )
)
```
I get the intended html:
```html
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<script src="bower_components/modernizr/modernizr.js"></script>
<script src="bower_components/foundation/js/foundation.min.js"></script>
```

**Comment by zordius** [comment]
Maybe you forget to enable FLAG_THIS or FLAG_HANDLEBARSJS ? please refer to this section: https://github.com/zordius/lightncandy#compile-options

**Comment by iwilliams** [comment]
Ah yes, FLAG_THIS seemed to do the trick! In the documentation it states the using FLAG_THIS will resolve `{{this}}` to `{{.}}`, but if I'm not mistaken `{{.}}` refers to the root document... When using FLAG_THIS if `{{this}}` is in fact resolving to `{{.}}`, wouldn't that give me the initial behavior that I did not want? Seems that maybe the documentation is backwards.

Anyways, thanks for the help. Great library!

**Comment by zordius** [comment]
Yes, {{.}} means {{this}} and  {{@root}} means root and {{../foo}} means parent foo. And, lightncandy support both mustache and handlebars and focus on performance, so we did not set default to either handlebars or mustache.
