### ISSUE TITLE
Generate function w/o external file save?

### ISSUE THREAD

**Issue by TomAuger** [zordius/lightncandy#156]
Hi, do you have a method or option that will return an executable function, rather than a PHP string that needs to be saved and `include`d in order to run?

IE:
``` php
$template = "<p>{{$test}}</p>";
$moustache = LightnCandy::compile( $template );
$moustache( array( "test" => "Hello, World" ) );
echo $moustache;
```

**Comment by TomAuger** [comment]
I see `LightnCandy::FLAG_BARE`, which gets me part way there (ie: strips out the <?php ?> tags).

But the result of `compile()` is still just a string, not a function. `eval()`ing the string results in an error ("Unexpected $end").

**Comment by TomAuger** [comment]
The best I can do is `eval( $moustache . ";" )` but somehow that just feels like I'm not using the library as you intended.

**Comment by zordius** [comment]
Base on the code here: https://github.com/zordius/lightncandy/blob/fc688e54e0c5a2b3a53c53dc635a14c807106652/src/lightncandy.php#L834

When your PHP settings are `allow_url_fopen` and `allow_url_include` (which is not secure) , you can get PHP function by `LightnCandy::prepare($phpCodeString)` without tmp file.

Another way is `eval()`, still not secure for production. If you do not care about secure and performance issue, you can use `LightnCandy::prepare()` directly.
