### ISSUE TITLE
error in nested helper

### ISSUE THREAD

**Issue by leite** [zordius/lightncandy#157]
Hi,

I'm having a error with nested helper since I updated your lib ...

```
Type: Exception
Message: Wrong variable naming as '(url_for "login")' in {{#form method="POST" action=(url_for "login") class="form-horizontal" }} ! You should wrap ! " # % & ' * + , ; < = > { | } ~ into [ ]
File: /home/leite/studies/slim/vendor/zordius/lightncandy/src/lightncandy.php
Line: 791
```

for more details I'm using these flags:
```
FLAG_ERROR_EXCEPTION | FLAG_ERROR_LOG | FLAG_INSTANCE | FLAG_MUSTACHE | FLAG_HANDLEBARS | FLAG_RUNTIMEPARTIAL
```

I'm using dev-master@fc688e54e0c5a2b3a53c53dc635a14c807106652

What are your thoughts on this matter?

**Comment by zordius** [comment]
it's a parsing bug, I will work on it later, thank you for reporting this!

**Comment by zordius** [comment]
Now it should be fixed on master, please try again, thanks.

**Comment by leite** [comment]
man, that was fast, it's working

thank you!
