### ISSUE TITLE
Lightncandy sometimes garbles JS functions in partials

### ISSUE THREAD

**Issue by mmontagna** [zordius/lightncandy#158]
When I use partials like this:

  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
....

Lightncandy does:
 $code = preg_replace('/\bfunction\s*\((.*?)\)\s*{/', 'function(\\1)use($sp){', $code);

Which causes the output JS function to look like:
(function(i,s,o,g,r,a,m) use($sp) {

Did I do something wrong? Disable/enable the wrong flags?

**Comment by zordius** [comment]
confirmed as a bug, will work on it, thank you for your reporting!

**Comment by zordius** [comment]
This bould be fixed by 9bd994ee9460aa0515ad26dca4a3b9b4eca6d18a , please try current master again, thanks!

**Comment by mmontagna** [comment]
Yes, that fixed it! Thanks :)
