### ISSUE TITLE
ArrayObjects in sections

### ISSUE THREAD

**Issue by brunobg** [zordius/lightncandy#159]
hi zordius!

lightncandy seems to treat empty ArrayObjects as if they are not empty. This is probably because `[] == false` but `new ArrayObject() == true` in PHP. Is there a way to handle that? 

Here's a sketch of the test case:

```
class Foo extends ArrayObject {
...
}

$mustache = '{{#data}}true{{else}false{{/data}}';
$foo = new Foo();
echo $renderer($mustache, ['data' => $foo]);
```

Expected: false. Actual result: true.

**Comment by zordius** [comment]
Now we align with handlebars behavior , a jsfiddle tests here: http://jsfiddle.net/k39aey8d/3/

**template**
```
{{#data1}}true{{else}}false{{/data1}},
{{#data2}}true{{else}}false{{/data2}},
{{#data3}}true{{else}}false{{/data3}},
{{#data4}}true{{else}}false{{/data4}},
{{#data5}}true{{else}}false{{/data5}},
{{#data6}}true{{else}}false{{/data6}},
{{#data7}}true{{else}}false{{/data7}},
```

**data**
```
var myArray = function () {};
var myObject = function () {};
myArray.prototype = new Array();

{
  data1: [],
  data2: {},
  data3: {ok: true},
  data4: new Array(),
  data5: new myArray(),
  data6: new Object(),
  data7: new myObject()
}
```

**handlebars.js output**
```
false,
true,
true,
false,
true,
true,
true,
```

It is tricky that we only need to care about native array object but not extended classes. I will create more tests for lightncandy to identify a correct PHP behavior.

**Comment by zordius** [comment]
Now should be fixed, but we can not deal with data5 case properly because it is far from PHP class behaviors.
