### ISSUE TITLE
Nested Partial Spacing

### ISSUE THREAD

**Issue by mmontagna** [zordius/lightncandy#160]
Given the template:
[space]{{> partials/header}}
And if header looks like:
HEADER
[space]{{> partials/masthead}}

and masthead looks like:
MASTHEAD

I expect the output to add the indentation of each template/partial to the next, like so:
[space]HEADER
[space][space] MASTHEAD

But instead I get:
[space]HEADER
[space]MASTHEAD

I am compiling using the following flags:
FLAG_ERROR_LOG, FLAG_HANDLEBARSJS 
FLAG_RUNTIMEPARTIAL, FLAG_STANDALONE
FLAG_PARENT, FLAG_WITH, FLAG_ERROR_EXCEPTION 
and the commit hash of 9bd994ee9460aa0515ad26dca4a3b9b4eca6d18a

**Comment by stephenwf** [comment]
Just a question, but since double spaces get ignored in HTML, what is the use case for preserving indentation level?

**Comment by mmontagna** [comment]
It breaks from the handlebars behavior so its unexpected. There isn't a particularly strong usecase, I agree, but handlebars templates aren't restricted to HTML, plain text templates are a thing too!

**Comment by zordius** [comment]
You can try to add an extra flag `FLAG_MUSTACHESP` , this enable the mustache spacing behavior.

**Comment by zordius** [comment]
self remind: if current handlebars.js enable the mustache spacing behavior by default , I should include this flag into FLAG_HANDLEBARSJS
