### ISSUE TITLE
Wikipedia Issues with Mustache server side renderings on hhvm

### ISSUE THREAD

**Issue by jdlrobson** [zordius/lightncandy#161]
Hi @zordius ! we are using Lightncandy Mustache implementation on MediaWiki / Wikipedia.org with HHVM. We are running into various problems which are preventing us from using it at mass.

We are seeing some very strange behaviour when we use Mustache if statements e.g. {{#foo}}foo exists!{{/foo}} {{^foo}}foo doesn't exist{{/foo}}

Would be great if you could give us your insight/expertise either here or preferably on this bug:
https://phabricator.wikimedia.org/T101918

**Comment by jdlrobson** [comment]
Update - we've traced it to an hhvm issue - https://github.com/facebook/hhvm/issues/5502 with eval. We are now trying to work out how best to work around this... any thoughts you have on easy ways to do this would be appreciated.

**Comment by stephenwf** [comment]
Hi there, if you're running into problems with creating the render closure for  the templates I would avoid using eval all together in HHVM. If you really dont want to save to a temp file, maybe try the data stream.

In your file: TemplateParser.php
```php
$base64 = base64_encode("<?php " . $code);
// cache $base64 if needed?
$renderer = include "data://text/plain;base64," . $base64;
```

According to this issue in HHVM: https://github.com/facebook/hhvm/issues/1051 the support for steams have been around for a while, so it should work fine (and faster than saving to disk).

**Comment by jdlrobson** [comment]
Thanks @stephenwf !

**Comment by zordius** [comment]
I remember there is an old issue discuss about eval and hhvm https://github.com/mattofak/knockoff/issues/3 , a better bet to load generated code is include() with either a file or an base64 url; You can use `$renderer = LightnCandy::prepare($phpStr);` , it do this for you. ( You can check the source code here: https://github.com/zordius/lightncandy/blob/b2fb300b20f75d4b7bd2d5fb6524a852733e9c8f/src/lightncandy.php#L835 )

Another good practice is pre-generate all templates into PHP for production, then include them by your own way.
