### ISSUE TITLE
Custom hbhelpers with conditional returns 1

### ISSUE THREAD

**Issue by pierot** [zordius/lightncandy#163]
I have a custom hbhelper with an if-like setup:

```
'is' => function($args) {
  $args = func_get_args();

  $base = array_shift($args);
  $options = array_pop($args);

  if(in_array($base, $args)) {
    return $options['fn']();
  }
  
  return $options['inverse']();
},
```

I can feed multiple arguments in and compare with a base value:

```
<p>{{#is "WORKS" "WORKS" "TEST"}}IT WORKS{{/is}}</p>
```

So here I see if `WORKS` equals `WORKS` or `TEST`.

But if the condition fails and I do not put an `{{else}}` in the template, the library returns a simple `1`.
So:

```
<p>{{#is "NOTWORK" "WORKS" "TEST"}}IT WORKS{{/is}}</p>
```

This will print a `1`, although it is supposed to render nothing.

What am I missing?

**Comment by zordius** [comment]
I just do a small tests and found when there is no `{{else}}` section, then `$options['inverse']` should be undefined, and an error like `Undefined index: inverse in fileName on line N` + `PHP Fatal error:  Function name must be a string` will happen.

So, in theory the `return $options['inverse']();` will never work. It's strange and different from your report, so we need more hint to find out what's wrong.

1. You can add more protection for `$options['inverse']`:

```php
  if(in_array($base, $args)) {
    return $options['fn']();
  }

  if (!isset($options['inverse']) { // when no {{else}} , return ''
    return '';
  }

  return $options['inverse']();
```

2. Add some error_log to make sure the flow. If the result still same with your report, we may need more  code from you to figure out the issue.

3. I should add some document for `{{else}}` <=> `$options['inverse']` , it's a good way for custom helper to detect the `{{else}}` block exists or not, then can do more interesting behaviors in the helper.

Thank you for your report!

**Comment by pierot** [comment]
Adding
```php
if (!isset($options['inverse'])) {
  return '';
}
```
does the trick. Thanks for the tip!
