### ISSUE TITLE
Parse error: syntax error, unexpected end of file when setting FLAG_BARE and using eval()

### ISSUE THREAD

**Issue by ct-jensschulze** [zordius/lightncandy#164]
When compiling a template with FLAG_BARE and directly executing it with eval() you get a parse error as the renderer function is not terminated with a semicolon.

```
$phpStr = \LightnCandy::compile($templateStr, [
        'flags' => \LightnCandy::FLAG_BESTPERFORMANCE |
            \LightnCandy::FLAG_ERROR_EXCEPTION |
            \LightnCandy::FLAG_HANDLEBARS |
            \LightnCandy::FLAG_RUNTIMEPARTIAL |
            \LightnCandy::FLAG_BARE
    ]);
```

The renderer will look like this:
```
return function ($in, $debugopt = 1) {
 ...
}
```

When directly executing with eval
```
$renderer = eval($phpStr);
```
following error is thrown
```
Parse error: syntax error, unexpected end of file
```

By adding a semicolon it can be directly executed with eval()

```
$renderer = eval($phpStr . ';');
```

So adding the semicolon directly in the Handlebars compiler would produce a cleaner php code.

**Comment by zordius** [comment]
Now it should be fixed at branch master, please try again. Thank you for your reporting!
