### ISSUE TITLE
preserve html conditional comments

### ISSUE THREAD

**Issue by reno1979** [zordius/lightncandy#165]
How do I prevent that conditiona html comments are removed when compiled??

**Comment by zordius** [comment]
I can not figure out the question, can you describe the issue more detail? thanks.

**Comment by reno1979** [comment]
The html conditional comments used to load ie specificaties stylesheets for
example, or in our case to load the correct jquery version.
Op 4 jul. 2015 17:41 schreef "Zordius" <notifications@github.com>:

**Comment by zordius** [comment]
Can you show me the sample template and expected output? Thanks. In theory, handlebars/lightncandy do not care about HTML format, it is generic for any text output.

**Comment by reno1979** [comment]
```
<![if lt IE 9]>
<p>Please upgrade.</p>
<![endif]>
```

**Comment by zordius** [comment]
I just tested with your sample template:
```php
<?php

require('src/lightncandy.php');

$template = <<<VAREND
<![if lt IE 9]>
<p>Please upgrade.</p>
<![endif]>
VAREND;

$code = LightnCandy::compile($template, [
    'flags' => LightnCandy::FLAG_HANDLEBARSJS,
]);

$render = LightnCandy::prepare($code);

echo $render(null);
?>
```

The output is:

```
<![if lt IE 9]>
<p>Please upgrade.</p>
<![endif]>
```

It works as expected.

**Comment by reno1979** [comment]
well that is odd, I'm glad though :)
