### ISSUE TITLE
PHP编译后的文件可以不生成吗？

### ISSUE THREAD

**Issue by nimojs** [zordius/lightncandy#166]
编译后生成的文件太多了我们服务器空间不够用。

或者有没有什么方法解决我们这个问题。

**Comment by zordius** [comment]
不生成的話每次都要重新編譯, 執行速度上會很慢喔.
此外要看你們所使用的framework是什麼, 檔案太多應該是framework造成的. lightncandy 本身內定會清除它自己所使用的暫存檔案, 理論上不會佔用空間.
