### ISSUE TITLE
Hook to change partial before storing

### ISSUE THREAD

**Issue by demil** [zordius/lightncandy#173]
Is there some way to have som hook to change partial before render, like

 'partial' => function ($partial) {
            return html_minify($partial);
        }

or best would be to have hook for prestored template not only partial

 'pre_write_templatel' => function ($partial) {
            return html_minify($partial);
        }
and i would minify all, main template and partials.

if there is not, how can i quickly hack for this feature?

Thank you very much.

**Comment by demil** [comment]
Or just for better explaining i need to wrap templates and partial for example:

'pre_write_templatel' => function ($template) {
return '<component id="test">'.$template.'</div>';
}

**Comment by zordius** [comment]
It's a really hard requirement if you like to do HTML minify. We can not promise everyone will create the template as pure , clean and valid HTML. check this case:

```
<{{#if ordered}}ul{{else}}ol{{/if}}{{#if classes}}class="{{#each classes}}{{.}} {{/each}}">
 <li>this is an example</li>
</{{#if ordered}}ul{{else}}ol{{/if}}>
```

When you replace handlebars tokens with !TOKEN! you will see:
```
<!TOKEN!ul!TOKEN!ol!TOKEN!!TOKEN!class="!TOKEN!!TOKEN!!TOKEN!">
 <li>this is an example</li>
</!TOKEN!ul!TOKEN!ol!TOKEN!>
```

We get `<!` , `ul` , `ol`, `class="` , `">` for this case and all of them are not valid HTML.

**Comment by demil** [comment]
i just gived example. 

What i really need is that i need to have function which will before compile partial do something with partial, change it or anything.

My specific is that i need before compile in specific situation to add class to first element of partial - BEFORE COMPILE.

**Comment by zordius** [comment]
ok I got it. I will add a hook for this, thanks.

**Comment by zordius** [comment]
Ya now it's done and please check the document about this feature: https://github.com/zordius/lightncandy#preprocess-partials , thanks.
