### ISSUE TITLE
dynamic partial

### ISSUE THREAD

**Issue by demil** [zordius/lightncandy#174]
this actually dont work:

You can use dynamic partial name by passing a custom helper as subexpression syntax, for example: {{> (foo)}} . the return value of custom helper foo will be the partial name. When you using dynamic partial, LightnCandy will compile all partial inside the partials option into template. (TODO: add an example to show how to provide partials across templates to reduce size)

i tried {{> (dynamic_partial)}}

**Comment by zordius** [comment]
I will update the DOC and make an example for this.

**Comment by zordius** [comment]
I just tested this feature and proved it works well. I also updated the document here: https://github.com/zordius/lightncandy#dynamic-partial . If you wanna try this feature yourself, you may start from this file: https://github.com/zordius/lightncandy/blob/master/tests/example_partials.php . Thanks.
