### ISSUE TITLE
Handlebars Comments throw exception

### ISSUE THREAD

**Issue by ct-jensschulze** [zordius/lightncandy#175]
I had a template with a commented out block in a partial with an {{each}}...{{/each}}.

The compile command throws an exception "Unexpect token: {{/each}} !"

As the comments are working correctly in the template itself, it's something with the partials.

template example:

```
<html>
<body>
{{!--
 {{each products}}
 <h1>{{name}}</h1>
 {{/each}}
 --}}
{{> partial}}
</body>
</html>
```

partial example:

```
{{!--
 {{each products}}
 <h1>{{name}}</h1>
 {{/each}}
 --}}
<h2>Test</h2>
```

By removing the {{/each}} in the partial it can be compiled

**Comment by zordius** [comment]
Yes, `{{/each}}` is unexpect because you did not start with `{{#each}}` , so you can change `{{each}}` with `{{#each}}` to fix this wrong template.

**Comment by zordius** [comment]
Sorry I realized this is related with comment, will try to fix it.

**Comment by zordius** [comment]
it should be fixed at current master, please try again, thanks.
