### ISSUE TITLE
support partial block

### ISSUE THREAD

**Issue by zordius** [zordius/lightncandy#178]
based on http://handlebarsjs.com/partials.html#partial-block

**Comment by doublejosh** [comment]
+1

**Comment by zordius** [comment]
now this feature is ready in 4347a78b3e96146644d6a645ac6306612a71dbc9 and wait for release

**Comment by zordius** [comment]
v0.89 released https://github.com/zordius/lightncandy/releases/tag/v0.89 , please try it, thanks.
