### ISSUE TITLE
support inline partial

### ISSUE THREAD

**Issue by zordius** [zordius/lightncandy#179]
based on http://handlebarsjs.com/partials.html#inline-partials

**Comment by oskarrough** [comment]
Hi, how is this coming along? Any way we can help?

**Comment by zordius** [comment]
Oh, now inline-partials is ready in my local branch but still can not pass 2 handlebars.js spec, I need some time to fix it. I just push the develop branch here: https://github.com/zordius/lightncandy/tree/v0.89-develop , you can try it if you are interesting in this feature.

**Comment by zordius** [comment]
now this feature is ready in 71130e69e0d65188c95a61d712635e4dca5a452f and waiting for release

**Comment by zordius** [comment]
v0.89 released https://github.com/zordius/lightncandy/releases/tag/v0.89 , please try it, thanks.
