### ISSUE TITLE
Error in scope handling

### ISSUE THREAD

**Issue by jayS-de** [zordius/lightncandy#182]
version: dev-master
git hash: 4c5c829c1efdc9a21e4ab451f55b8db867dff6b6

Seems that an if block changes the scope, which is not correct. 

Example script:
```
<?php
require __DIR__.'/../vendor/autoload.php';

$template = '
{{#each testfacet.options}}
  {{#if children}}
    correct scope: {{../testfacet.key}}
    wrong scope: {{../../testfacet.key}}
  {{/if}}
{{/each}}';

$phpStr = \LightnCandy::compile(
    $template,
    [
        'flags' => \LightnCandy::FLAG_BESTPERFORMANCE |
            \LightnCandy::FLAG_ERROR_EXCEPTION |
            \LightnCandy::FLAG_NAMEDARG |
            \LightnCandy::FLAG_ADVARNAME |
            \LightnCandy::FLAG_RUNTIMEPARTIAL |
            \LightnCandy::FLAG_HANDLEBARSJS
    ]
);

$php_inc = 'renderer.php';
file_put_contents($php_inc, $phpStr);
$renderer = include $php_inc;

$data = [
    'testfacet' => [
        'key' => 'correct key',
        'options' => [
            [
                'children' => ['something'],
                'testfacet' => [
                    'key' => 'wrong key'
                ]
            ]
        ]
    ]
];
echo $renderer($data);     
```

Output:
```
correct scope: wrong key
wrong scope: correct key
```          
                      
See documentation for handlebars on this topic:

The exact value that ../ will resolve to varies based on the helper that is calling the block. Using ../ is only necessary when context changes, so children of helpers such as each would require the use of ../ while children of helpers such as if do not.

```
{{permalink}}
{{#each comments}}
  {{../permalink}}

  {{#if title}}
    {{../permalink}}
  {{/if}}
{{/each}}
```

**Comment by zordius** [comment]
Hello, the LightnCandy behavior is exact same with handlebars.js , please check this jsfiddle: http://jsfiddle.net/pkqthLm9/

Not all block helper will change the context. For example, the `{{#if}}` will not change the context.
You may also check https://github.com/zordius/lightncandy#handlebarsjs-custom-helper to know more about handlebars.js internal helper working model.

**Comment by jayS-de** [comment]
I see your point. And now the funny part. And I found out why I had a problem. HandlebarsJS 4 changed the behaviour on this topic.

See https://github.com/wycats/handlebars.js/issues/1028 and https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v400---september-1st-2015

**Comment by zordius** [comment]
Good, I will align with new handlebars.js 4+ and make this break change, thank you!

**Comment by zordius** [comment]
Add new jsfiddle to test on handlebars 4.0.4: http://jsfiddle.net/pkqthLm9/1/ , output:

```
    correct scope: correct key
    wrong scope: 
```

**Comment by fesja** [comment]
Glad you've already fix it :+1:  When are you planning on releasing this version? thanks!

**Comment by zordius** [comment]
There are a lot of breaking changes in new version and I am working hard to adopt handlebars 4.0 features....I hope I can include most of missing features in the new version (v0.89-develop) , then it can be released. (ASAP, maybe eoy)

**Comment by fesja** [comment]
thanks!

**Comment by zordius** [comment]
v0.89 released https://github.com/zordius/lightncandy/releases/tag/v0.89 , please try it, thanks.
