### ISSUE TITLE
Added support for custom delimeters when compiling a template

### ISSUE THREAD

**Issue by zordius** [zordius/lightncandy#191]
refer to #185

**Comment by seguer** [comment]
In addition this will need to support custom delimiters when attempting to echo a variable as the raw value.

ie. ``{{{foo}}}`` or ``[[[foo]]]`` (if delimiter is ``[[ ]]``?)

However you can change custom delimiters to be something like ``<% foo %>`` so we'd need a second option to actually change how raw is parsed (in this case you might want ``<%% foo %%>``

@zordius do you have an ETA on this, and/or is there any way I can help?

**Comment by zordius** [comment]
When the delimiter is `[[foo]]` , `[[{foo}]]` means raw value. Another way is the `&` operator.

So, `{{{foo}}}` means `{{&foo}}` and when delimiter is `[[ ... ]]` you can use `[[{foo}]] or `[[&foo]]` .

**Comment by zordius** [comment]
This feature can be done soon today (in master branch)

**Comment by seguer** [comment]
Excellent, thanks a lot!

**Comment by zordius** [comment]
Now this feature is ready in master branch, please check the document, thanks.

**Comment by seguer** [comment]
Hi @zordius I've tested and verified that this has solved the issue originally raised in #185.

Thanks for the speedy resolution!
