### ISSUE TITLE
Option suggestion: use statements?

### ISSUE THREAD

**Issue by darkphoenixff4** [zordius/lightncandy#193]
I noticed that the new release now uses full namespaces, and that the runtime is now imported via use statement.  Since I ran into this problem using Lightncandy before, can I suggest allowing the programmer to give Lightncandy a list of use statements to add to the use block at the top along with the runtime?  I ended up having to constantly call the full class name plus namespace every time I wanted to use a helper because my use aliases aren't imported into the final compiled product, but the shortform calls to my helpers are.

**Comment by zordius** [comment]
Ya it's a good idea.

A. Before this we already have `renderex` compile time option to extend inside the render function, but `use` must before any other statements. So I can create a new option `renderuse` to make customization of `use` inside the render function.

B. Another way to resolve this is.......we already have `FLAG_BARE` option to generate code without `<?php` and `?>` . Maybe we can change the way of work flow:

1. LightnCandy::compile() : Always generate code without `<?php` and `?>`
2. Save template: developers can choose any way to store the template. And, when they save the template, they can add any `use` or other statements before render function.
3. LightnCandy::prepare() : Default to include the php code as `"<?php $code ?>"` . And, developers still can put customized `$phpcode` into `prepare()`.
4. Remove `FLAG_BARE` option. Now we always generate code without `<?php` and `?>` .

I will vote for B. .....How do you think?

**Comment by jayS-de** [comment]
I would prefer the variant 3. As it's the variant which will not break existing code. Btw. it would also be cool to have something like the renderex for partials. So it would be possible to build a partial/block caching infrastructure.

**Comment by zordius** [comment]
@jayS-de Thank you for your input! I think we can try to improve partial customization with these ways:

* make lightncandy render function interface align with handlebars.js, then we can pass partials into render function:
```php
$render($data, array('partials' => array( ....)));
```

* add another API to compile partial, then developers can implement their own partial storage.

I will open another issue to deal with this.

**Comment by zordius** [comment]
Hello @darkphoenixff4 :

I did some modification on lightncandy, you can try to do your own customization in this way:

```php
use LightnCandy\LightnCandy;

$template = 'Hello, {{foo}}!';
$php = LightnCandy::compile($template);
$useStr = <<<VAREND
use \\MyTools\\MyClassA;
use \\MyTools\\MyClassB as MCB;
....
VAREND;

// Now the render function will know MyClassA and MCB
$render = LightnCandy::prepare($useStr . $php);

$data = array('foo' => 'world');

echo $render($data);
```

Please try current master, thanks.

**Comment by darkphoenixff4** [comment]
I think that ought to work.  The situation that lead me to conclude LNC could really use this feature involved Closure-based partials being embedded directly in the templates; when they were directly embedded as opposed to being referenced by a class & method, I kept getting errors if I used any kind of shortform at all.  I eventually gave up on this approach entirely because I would have had to embed fully qualified names into all my partials.  I kind of like the idea of being able to customize the code around the template function, since besides use statements it'd be useful to be able to namespace the template functions, plus it'd be a good spot to add a require for Composer dependencies (which I did to make the templates more standalone, though I don't believe it was actually necessary).

**Comment by jayS-de** [comment]
There is a small issue with removing the FLAG_BARE

the php string returned by compile is missing a colon. Which means you have to add it before on saving the file. And the also the returned string is no valid php ;)

```
$phpStr = LightnCandy::compile($contents);
file_put_contents($file, '<?php' . PHP_EOL . $phpStr . ';');
```

**Comment by zordius** [comment]
thank you for the remind!

**Comment by zordius** [comment]
738a1339af1dd93e72078ad67fbffcfe6d62aa4b in master should fix this, please try it, thanks.
