### ISSUE TITLE
partial customization

### ISSUE THREAD

**Issue by zordius** [zordius/lightncandy#194]
refer to #193 .

* make lightncandy render function interface align with handlebars.js, then we can pass partials into render function:
```php
$render($data, array('partials' => array( ....)));
```

* add another API to compile partial, then developers can implement their own partial storage.

**Comment by jayS-de** [comment]
This would be a nice feature. Should be possible to add partials as rendered html as well as have the ability to use a callable. Because some partials may be rendered in a loop and it would be not very useful to place always the same html inside ;)

**Comment by zordius** [comment]
Not sure, can you show me some use case? thanks!

**Comment by jayS-de** [comment]
For example a product overview:

{{#each products}}
   {{> catalog/product-detail }}
{{/each}}

When you could overwrite the partial only with prerendered HTML every product would have the same content. When you could overwrite the partial with a callback you could decide inside the callback which prerendered HTML should be used based on the partials context.

**Comment by zordius** [comment]
Can you use dynamic partial?

```
{{#each products}}
{{> (product_partial_helper) }}
{{/each}}
```

And then you can use the `product_partial_helper` to detect the context and decide a partial to render the product. (The `product_partial_helper` can return a partial name, then the partial name will be used to render)

**Comment by jayS-de** [comment]
Depends. We are using a shared template for different languages. So i can't adjust the templates that easily.

The advantage of just overwriting partials at render time with a callback would be, that the templates would work out of the box, without any implementation of the dynamic partials. But could replaced anytime at runtime.

**Comment by zordius** [comment]
Now lightncandy 0.91+ can support render time partial overwrite and ::compilePartial() , it's already good for partial customize. For the requirement from @jayS-de , after I reviewed this I think the best practice is 'align features between lightncandy and handlebars.js' . That means, I should not provide a runtime callback for partial customization only works in lightncandy but not works in handlebars.js . The best bet is using the `dynamic partial` feature which already defined in handlebars.js, or use `{{#if }}{{> foo}}{{else if}}{{> bar}}{else if}}{{> moo}}{else if}}...` for runtime partial switching use case.

Thank you!
