### ISSUE TITLE
Why was FLAG_BARE removed?

### ISSUE THREAD

**Issue by claviska** [zordius/lightncandy#197]
In 0.9, FLAG_BARE was removed and the default behavior changed so that `<?php` is no longer included in compiled templates. That means using the documented example no longer works without adding it in yourself.

This is what the docs show, for example:

```php
file_put_contents($php_inc, $phpStr);
$renderer = include($php_inc);
```

But you actually need to do this:

```php
file_put_contents($php_inc, '<?php ' . $phpStr);
$renderer = include($php_inc);
```

Otherwise when you include it, the file isn't executed and you get a string instead. I'm wondering why this is the new default behavior.

I also noticed that the deprecated [`prepare()` method](https://github.com/zordius/lightncandy/commit/8942155d20#diff-9f16da8c27dd5925f107ad4c0dfb2175R108) was updated in 8942155d20 so that the `<?php` is there now.

Was this an oversight, or is it intentional that `<?php` should be added in manually now?

**Comment by zordius** [comment]
Yes I need to update the example. This change is to make people can customize their compiled code more easily, refer to #193 .

**Comment by claviska** [comment]
Thanks. Just wanted to make sure this wasn't an oversight :)
