### ISSUE TITLE
FLAG_STANDALONEPHP still requires SafeString

### ISSUE THREAD

**Issue by jonathantneal** [zordius/lightncandy#198]
When I use `FLAG_STANDALONEPHP`, the resulting string includes `use \LightnCandy\SafeString as SafeString` which is not used, but would seem to suggest my precompiled method is not stand-alone.

```php
$phpStr = LightnCandy::compile($template, Array(
	'flags' => LightnCandy::FLAG_STANDALONEPHP
));
```

Am I using this incorrectly?

Example:

Render an empty template:
```php
use LightnCandy\LightnCandy;

$phpStr = LightnCandy::compile('', Array(
	'flags' => LightnCandy::FLAG_STANDALONEPHP
));

echo $phpStr;
```

Resulting `$phpStr`:
```php
use \LightnCandy\SafeString as SafeString;return function ($in, $options = null) {
    $helpers = array();
    $partials = array();
    $cx = array(
        'flags' => array(
            'jstrue' => false,
            'jsobj' => false,
            'spvar' => false,
            'prop' => false,
            'method' => false,
            'lambda' => false,
            'mustlok' => false,
            'mustlam' => false,
            'echo' => false,
            'partnc' => false,
            'knohlp' => false,
            'debug' => isset($options['debug']) ? $options['debug'] : 1,
        ),
        'constants' =>  array(
            'DEBUG_ERROR_LOG' => 1,
            'DEBUG_ERROR_EXCEPTION' => 2,
            'DEBUG_TAGS' => 4,
            'DEBUG_TAGS_ANSI' => 12,
            'DEBUG_TAGS_HTML' => 20,
        ),
        'helpers' => isset($options['helpers']) ? array_merge($helpers, $options['helpers']) : $helpers,
        'partials' => isset($options['partials']) ? array_merge($partials, $options['partials']) : $partials,
        'scopes' => array(),
        'sp_vars' => isset($options['data']) ? array_merge(array('root' => $in), $options['data']) : array('root' => $in),
        'blparam' => array(),
        'runtime' => '\LightnCandy\Runtime',
    );

    return '';
};
```

**Comment by zordius** [comment]
It is an interesting part of `standalone` . After v0.90 we changed the custom helper interface to align with handlebars.js and introduce `SafeString` class to detect custom helper response type. This class is required by Runtime or your custom helper. When I do this change I decide to keep this class there to make it simple.

If we want to do real `standalone` :

* I can rename `SafeString` class into `SafeStringXXXXXXXX` to prevent redefined class for every compiled PHP files.
* If many standalone PHP files be included, the memory usage may be very large when we created many classes inside these PHP files.
* But, for external custom helpers, they can not know real `SafeStringXXXX` class name and this solution will cause big problem.

```php
use LightnCandy\SafeString;
function myCustomHelper () {
    return new SafeString($myResult);
}

// The SafeString class inside the $render may be SafeStringABCD123
// and the instanceof validation will fail.
$render($data, array(
    'helpers' => array(
        'myCustomHelper'
    )
);
```

Refer to https://github.com/zordius/lightncandy/blob/9050767c5b2e66f7f45fe8e4aea0b9706617a2e9/src/Runtime.php#L244

So I decide to not make the `SafeString` standalone.

Do anyone figure out better solution for this issue?

**Comment by zordius** [comment]
:bulb: A small enhancement can be done is: When `Runtime::enc()` not be used, the `SafeString` can be removed.

**Comment by zordius** [comment]
I just got an idea, maybe I can use http://php.net/manual/en/function.class-exists.php to prevent dupe class declaration issue. Will try to work on it.

**Comment by zordius** [comment]
After 6cda56c5523c62d72a44bebf45cb914d80e5696a we do not need SafeString when we compile() with FLAG_STANDALONEPHP , now in branch master, please try it, thanks.

**Comment by zordius** [comment]
released in https://github.com/zordius/lightncandy/releases/tag/V0.91
