### ISSUE TITLE
Symfony3 integration

### ISSUE THREAD

**Issue by jayS-de** [zordius/lightncandy#200]
Hi zordius,

i just committed my symfony3 bundle for LightnCandy

https://packagist.org/packages/jays-de/handlebars-bundle

would be cool if you could link it in the readme file

Greetings

Jens

**Comment by zordius** [comment]
Added. A suggestion: add a README.md in your git and add more detail about it. :smile:

**Comment by jayS-de** [comment]
Yeah just finished the first working version. ;)
