### ISSUE TITLE
how to resolve helpers ?

### ISSUE THREAD

**Issue by DragorWW** [zordius/lightncandy#201]
For partial i can use partialresolver param. How to make like options for helpers?

**Comment by zordius** [comment]
It's a good idea, will work on it.

**Comment by zordius** [comment]
Wait a minute. Now lightncandy use helper list to do compile() , if we provide something like `helperresolver` then we will do it many times when we deal with almost all handlebars tags: {{foo}} (is foo a helper?) {{#bar}} (is bar a helper, again?) .....

Anyway, It should be safe to provide this option.

**Comment by jayS-de** [comment]
Actually the question is, if the helper needs to be compiled inside the template or if it can't just be a callable

**Comment by jayS-de** [comment]
Oh wait, i just saw the exthelper flag :)

**Comment by zordius** [comment]
Now we support `helperresolver` option. The resolver can return the helper name string or a callable, the input params are compile context and the helper name; refer to https://github.com/zordius/lightncandy/blob/2ffddedd2c09f54852eb303ec153fbf3fae70c51/tests/regressionTest.php#L896-L924 for sample codes.

Please try current master for this new feature, thanks.
