### ISSUE TITLE
V8js support?

### ISSUE THREAD

**Issue by jayS-de** [zordius/lightncandy#203]
I'm curios if the V8js extension would be worth a try out. So one could directly use the handlebars JS sources.

**Comment by zordius** [comment]
Ya, I did some google search and I found this: https://github.com/kynx/v8js-handlebars ! This started from  3 month ago, the only issue is `none of the major Linux distros ship with a version of V8 > 3.24.6, which V8Js depends on.` . Maybe a good solution in near future!

Here is another project https://github.com/crxgames/PHPHandles proved this concept at 3 years ago.
