### ISSUE TITLE
Partial block is duplicating content

### ISSUE THREAD

**Issue by oskarrough** [zordius/lightncandy#204]
Hi, I have the following `test.hbs` partial:

```hbs
<h1>{{name}}: {{> @partial-block}}</h1>
```

And an `index.hbs` template like this:

```hbs
{{#> "test" name="Samuel"}}Fish{{/"test"}}
{{#> "test" name="Oskar}}Lion{{/"test"}}
```

It renders like this:

```markup
<h1>Samuel: Fish</h1>
<h1>Oskar: Fish</h1>
```

What I would expect is for me to be a lion, not a fish:

```markup
<h1>Samuel: Fish</h1>
<h1>Oskar: Lion</h1>
```

Any idea? I'm on lightncandy 0.90.

**Comment by jayS-de** [comment]
Tried it at http://tryhandlebarsjs.com/ with this template

```
{{#*inline "test"}}
  <h1>{{name}}: {{> @partial-block}}</h1>
{{/inline}}

{{#> test name="Samuel"}}Fish{{/test}}
{{#> test name="Oskar"}}Lion{{/test}}
```

HTML Output was:

```
  <h1>Samuel: Fish</h1>
  <h1>Oskar: Lion</h1>
```

**Comment by oskarrough** [comment]
Thank you. It works for me as well with handlebars.js but not with lightncandy.

**Comment by zordius** [comment]
Now lightncandy only use one global place to handle partial blocks , for this use case we need to change the design to allow different content per block.

**Comment by zordius** [comment]
It should be fixed now in master branch, please try it, thanks!
