### ISSUE TITLE
Generated php can give PHP parse errors

### ISSUE THREAD

**Issue by workguy66** [zordius/lightncandy#205]
Errors in template translate to errors in php

try rendering this

```

{{#if test}}

Hello, the closing if tag is omitted on purpose

```

it will give you a parse error: 

`PHP Parse error:  syntax error, unexpected ';' in /tmp/lci_0OJUZl on line 3`

instead of parse errors it should throw an exception

**Comment by zordius** [comment]
Sorry, I can not reproduce this issue, can you show me your compile flags or the sample code? thanks.

**Comment by workguy66** [comment]
```
        # LightnCandy is a flexible and light implementation of both Mustache and Handlebars
        # it compiles the template into a temporary file and then renders it with the provided variables
        $tmpl = LightnCandy::compile($tmpl, array(
            'basedir' => Yii::getPathOfAlias('application') . '/views/emailPartial',
            'fileext' => '.php',
            'flags' => LightnCandy::FLAG_INSTANCE | LightnCandy::FLAG_HANDLEBARS | LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_ERROR_EXCEPTION,
        ));
        $renderer = LightnCandy::prepare($tmpl);
        var_dump($renderer($params));
```

I discovered that both of the following cases give errors

```
$params = ['name'=>'Tester','cond'=>'0'];
        $tmpl = '<p>
    Dear {{name}},
</p>
<p>
    Thank you for taking the time to attend the Seminar.
</p>
{{#if cond}}
    <p>
        To view a video of the main points that were covered in the seminar please go to:
    </p>
{{else}}
    <p>
        No videos
    </p>
{{/if}}
{{> footer_en}}';
```


```
        $params = ['name'=>'Tester','cond'=>'0'];
        $tmpl = '<p>
    Dear {{name}},
</p>
<p>
    Thank you for taking the time to attend the Seminar.
</p>
{{#if cond}}
    <p>
        To view a video of the main points that were covered in the seminar please go to:
    </p>
{{else}}
    <p>
        No videos
    </p>

{{> footer_en}}';
```

The footer_en file contains:

```
<p>
    Regards<br/>
    {{#if data.SalesPersonName}}
    <strong>{{data.SalesPersonName}}</strong><br/>
    {{/if}}
    {{data.OnBehalfOf}}
</p>
{{#if data.WorldOrgLogoUrl}}
<p>
    <img src='{{data.WorldOrgLogoUrl}}' alt='{{data.WorldOrgName}} logo'>
</p>
{{/if}}
<p>
    {{#if data.UseSalesPersonPhone}}
    Direct numbers:<br/>
    US {{data.phoneUs}}<br/>
    UK {{data.phoneUk}}
    {{else}}
    Office numbers:<br/>
    US {{data.phoneUs}}<br/>
    UK {{data.phoneUk}}
    {{/if}}
</p>
```


The error seems to be that it confuses the footer partial with the closing tag or something




On 2 February 2016 at 07:39, Zordius <notifications@github.com> wrote:
Sorry, I can not reproduce this issue, can you show me your compile flags or the sample code? thanks.

**Comment by jayS-de** [comment]
```
...
{{else}}
    <p>
        No videos
    </p>

{{> footer_en}}';
```

This should be an error in any case, as the closing tag is missing. It is also not allowed with HandlebarsJS: (Error(s): Error: Parse error on line 42: .../p>{{> footer_en}} ---------------------^ Expecting 'OPEN_ENDBLOCK', got 'EOF')

**Comment by zordius** [comment]
Current lightncandy do not have 'basedir' or 'fileext' option, it should be old version. I suggest you to upgrade to new version.

For version >= 0.89 , I just tested these cases:

```
1. {{#if foo}}Hello
2. {{#if foo}}Hello{{else}}
3. {{#if foo}}Hello{{else}}World
4. {{#if foo}}Hello{{else}}World{{> test}}
```

I can get `Unclosed token {{#if foo}} !!` for all these 4 cases.

```
5. {{else}}
6. {{else}}World
7. {{else}}World{{> test}}
```

For these 3 we can always get `{{else}} only valid in if, unless, each, and #section context` error.

**Comment by workguy66** [comment]
Must be an old version issue then, the version is v0.22
Sorry to have wasted your time
