### ISSUE TITLE
dynamic partial dont work from file, only from partial inserted in code

### ISSUE THREAD

**Issue by demil** [zordius/lightncandy#212]
function dynamic_partial($args) {
  return $args[0];
}

{{(>dynamic_partial data.partial}}

only works when we inserted data.partial partial name in code, but it not resolving it from file.

**Comment by zordius** [comment]
Maybe you should use `{(>(dynamic_partial data.partial)}}` ? Or it just a typo.

For the function `dynamic_partial` , it will return a name for partial, but the partial may not compiled into the render function. For example, your compile the template with partials `foo1` and `foo2`, but the `dynamic_partial` returns `foo3` .....neither handlebars.js nor lightncandy can handle this case. document: https://zordius.github.io/HandlebarsCookbook/0028-dynamicpartial.html

You should provide all possible partials to the render function when you run it.

**Comment by demil** [comment]
It was typo.

it is: {(>(dynamic_partial data.partial)}}

but it resolves only if partial was inserted in code.

For example if data.partial is "content"

it will not search for /partials/content.html

but if i have {{>content}} partial before in code {{>(dynamic_partial "content")}} will work, otherwise it will eork only if i put $options['partials']['content'] = 'partial content';

**Comment by zordius** [comment]
There is no 'resolve from file' feature in handlebars.js nor in lightncandy. You may go with one of these approach:

1. resolve all partials => compile => render (register all partials before you compile. will make render function bigger when using lightncandy + dynamic partial)
2. compile => resolve all partials => render (register all partials before you render)

In this document you can see how to send partials into handlebars.js render function ( https://zordius.github.io/HandlebarsCookbook/0028-dynamicpartial.html ) , it is something like:

```javascript
render(data, {
 partials: {
  "bar1": "Hello",
  "bar2": "World"
}});
```

With lightncandy, you can do this:

```php
// Resolve all partials
$partials = array();
foreach ($partials as $name => $file) {
    // Use same $options with compiled $render will be better.
    $partials[$name] = LightnCandy::compilePartial(file_get_contents($file), $options);
}

// Render with all partials
echo $render($data, array(
    'partials' => $partials
));
```

**Comment by zordius** [comment]
#207 will doc about this more

**Comment by zordius** [comment]
Please refer to https://zordius.github.io/HandlebarsCookbook/9004-partials.html#CompileWithoutPartials and https://zordius.github.io/HandlebarsCookbook/9004-partials.html#RuntimePartials , thank you.
