### ISSUE TITLE
Error when using custom helper and {{#if}}{{else if}}{{/if}}

### ISSUE THREAD

**Issue by jaysee** [zordius/lightncandy#213]
The PHP Code:
-------------

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
{{#if failed}}
    test failed
{{else if test}}
    {{#myif test}}
        myif is OK
    {{/myif}}
{{/if}}
VAREND;

// Helpers (from github example):
$helpers = Array(
      'myif' => function ($conditional, $options) {
        if ($conditional) {
          return $options['fn']();
        }
        if (isset( $options['inverse'] ) ){
          return $options['inverse']();
        }
        return "";
      }
      );

// Partials:
$partials = array(
    'bar' => 'no usage of partials',
);

$php = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS,
  'helpers' => $helpers,
  'partials' => $partials,
));

echo "Generated PHP Code:\n$php\n";

// Input Data:
$data = array(
  'test' => 1
);

$render = LightnCandy::prepare($php);
echo "Result:\n" . $render($data);
```

The Issue:
----------
This failed by a parse error :
Parse error: syntax error, unexpected ':' in /tmp/lci_wdvp96 on line 41 

if a change the template by replace the {{else if test}} by a simple {{else}}, it works (result is "myif is OK ")

{{#if failed}}
    test failed
{{else}}
    {{#myif test}}
        myif is OK
    {{/myif}}
{{/if}}

It also works if I use a standard {{#if}} block instead of {{#myif}}

Strange or do i misunderstand something ? (it works using handlebarjs)

thanks

**Comment by zordius** [comment]
Thank you for your report! It should be fixed in current master branch, please try it, thanks!

**Comment by jaysee** [comment]
Works like a charm, thanks you!
