### ISSUE TITLE
Can't return SafeString when FLAG_BESTPERFORMANCE is enabled

### ISSUE THREAD

**Issue by claviska** [zordius/lightncandy#215]
The PHP Code:
-------------

```php
require_once('./vendor/autoload.php');
use LightnCandy\LightnCandy;

function my_helper1 () {
    return new SafeString('<div>test</div>');
}

$template = '{{my_helper1}}';

$phpStr = LightnCandy::compile($template, array(
    'flags' => LightnCandy::FLAG_HANDLEBARS | LightnCandy::FLAG_BESTPERFORMANCE,
    'helpers' => array(
        'my_helper1'
    )
));
$renderer = LightnCandy::prepare($phpStr);
echo $renderer();
```

The Issue:
----------

Since 6cda56c5523c62d72a44bebf45cb914d80e5696a, it appears impossible to return a SafeString from a custom helper when `FLAG_BESTPERFORMANCE` is enabled.

The helper will always output an encoded string regardless of the second SafeString argument, which is undesirable.

Expected result is:

```html
<div>test</div>
```

Actual result:

```html
&lt;div&gt;test&lt;/div&gt;
```

Disabling `FLAG_BESTPERFORMANCE` yields the correct behavior.

**Comment by zordius** [comment]
In #198 we try to deal with FLAG_STANDALONEPHP and the SafeString class issue. After the fix, all custom helpers should works well no matter FLAG_STANDALONEPHP flag is on or off. The trick is patching all custom helpers and translate all `\LightnCandy\SafeString` into `LS` (the standalone version of SafeString) .

But I forget to add a document about this. For all custom helpers, if they try to return SafeString instance, they should do this:

```
function my_helper1 () {
    return new \LightnCandy\SafeString(......);
}
```

But should not do this:

```
function my_helper1 () {
    return new SafeString(......);
}
```

I will refine document for this, thank you for your report!

**Comment by zordius** [comment]
Document updated and online now: https://zordius.github.io/HandlebarsCookbook/9003-helperescaping.html

**Comment by claviska** [comment]
Beautiful, thanks for the prompt clarification. I was using the full namespace but omitted the preceding slash. Must have been late :)

Just a heads up! LightnCandy is being used as the Handlebars library in a new open source blogging platform called [Particle](http://www.particle.software), which will be launching on Kickstarter next week. Check the website for the link, or follow [@getparticle](http://twitter.com/getparticle) to get notified if you're interested!
