### ISSUE TITLE
Add {{array.length}} evaluation support

### ISSUE THREAD

**Issue by jaysee** [zordius/lightncandy#216]
The PHP Code:
-------------

```php
header("content-type: text/plain");
require '../includes/lib/LightnCandy/loader.php';
use LightnCandy\LightnCandy;

//require('./vendor/autoload.php');
//use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
ARRAY.LENGHT={{myArray.length}}
VAREND;

// Helpers - none
$helpers = Array();

// Partials - none
$partials = array();

$php = LightnCandy::compile($template, array(
              				     // Used compile flags
                                             'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS,
                                             'helpers' => $helpers,
                                             'partials' => $partials,
                                             ));

echo "Generated PHP Code:\n$php\n";

// Input Data:
$data = array(
	      'myArray' => array( 1, 2, 3, 4, 5 )
              );

$render = LightnCandy::prepare($php);
echo "Result:\n" . $render($data);
```

The Issue:
----------
Hi,

As in handlebars, myArray.length should returns count( $array )
should works for "helpers" so {{#if myArray.length}} doThings {{/if}}

Thanks again

**Comment by zordius** [comment]
Ya I ever thinking about this feature but the performance cost is big.

```php
// Original code to render test.length
echo (is_array($in['test']) && isset($in['test']['length']))
     ? $in['test']['length']
     : '';

// To support Array.proto.length in PHP
echo (is_array($in['test']) && isset($in['test']['length'])) 
     ? $in['test']['length']
     : (is_array($in['test']) ? count($in['test'] : '');
```

Another problem is: PHP associative array may means `{}` or `[]` in JavaScript, we need do more type detection than `is_array()` to figure it.

But, so far we have something like FLAG_JSOBJECT to simulate JavaScript proto.toString() behavior, maybe we can do this with a new compile option....for someone like to have this feature even with big performance cost.

It is dangerous. Maybe someday we need to support more native methods.... Array.proto.* or Object.proto.* .

**Comment by jaysee** [comment]
Hi,

yes, there is a cost, but it should only became a cost when it is called, not for all usages. So it doesn't alter the current performances of others features, so it's not a reall performance cost.

I think the "count()" test should ONLY by used when the looked "key" is "length", not for all others "keys" (i don't really see how the internal code is working, so perhaps it already was your suggestion in your sample code)

btw, Array.length can be used in test condition (and custom helpers args) as in "echo" token, i mean
```
LENGHT={{myArray.length}} // echo array length
{{#if myArray.length}}yes{{else}}no{{/if}} // (yes this is kind of dumb, as {{#if myArray}} would work the same, but for custom helpers, we could wan't to known the number of entries (in fact I need that one :) ).
```

And yes... PHP arrays are shitty for this kind of things, need to test more thing to evaluate if this is an Object or an Array...

A new flag could be added for this feature, but i think too much flags makes the thing harder to see what can/can't be done. And as it doesn't cost perfs hit if not used... a warning should do the thing ? But it' up to you to implement as you think the thing in the global project.

**Comment by stevejordan** [comment]
Would something like this work as an associative-or-not test:

```php
function isAssocitiveArray($arr) {
    return is_array($arr) && 0 === array_keys($arr)[0];
}
```

**Comment by jayS-de** [comment]
It's not working as you can see here:

https://3v4l.org/GT13c

**Comment by stevejordan** [comment]
https://3v4l.org/aqeC4 seems the fastest on `7.0`, but a good old foreach fastest for older versions: https://3v4l.org/NvO1F/perf

**Comment by jayS-de** [comment]
The performance graph doesn't allow to tell anything about the perfomance. It's the runtime for the whole script. Including parsing etcpp. And 10 to 20ms would be a lot.

Here just the detection times:
https://3v4l.org/lLtqE <-- range
https://3v4l.org/eabkB <-- foreach

Btw the foreach could be optimized to directly break if there is one non-numeric index

**Comment by stevejordan** [comment]
You're right. The choice of implementation looks like a difficult one, the results are so variable accross the php versions.

Good idea about the `break`.

**Comment by jayS-de** [comment]
Just ran it in a 100k loop. the foreach seems to be more efficient. But didn't had time for a closer look at the results

https://3v4l.org/AXXSq/perf#tabs <-- foreach
https://3v4l.org/YtW1G/perf#tabs <-- range

**Comment by zordius** [comment]
Now Lightncandy using this: https://github.com/zordius/lightncandy/blob/ef104e433e9198955072a4e90870a5e2da09962f/src/Encoder.php#L65 , do not know `array_diff_key()` is better than `range()` or not.

Another question is: if we testing on `{1:a 2:b 3:c 4:d .... 100:f, 100a: g}` , the `foreach` implementation still be the better one?

**Comment by stevejordan** [comment]
Looks like the `array_diff_keys` method is fastest:

https://3v4l.org/eOapU/perf#tabs [array_diff_keys]
https://3v4l.org/UgPTX/perf#tabs [foreach]

**Comment by zordius** [comment]
Current branch master supports {{array.length}} lookup (but not do Object {} detection) , please try it, thanks.

**Comment by zordius** [comment]
check these test cases: https://github.com/zordius/lightncandy/blob/3d6dabb9f5bf9852b11afa5739268d54953ac65f/tests/regressionTest.php#L974-L992

**Comment by jaysee** [comment]
Nice!

works for me, using flag LightnCandy::FLAG_HANDLEBARSJS!!

Thanks a lot!
