### ISSUE TITLE
LightnCandy in Particle! Also, consider using semver?

### ISSUE THREAD

**Issue by claviska** [zordius/lightncandy#217]
Hey @zordius! Just a heads up since I can't find you on Twitter.

I'm using LightnCandy in a blogging platform I built called Particle, which [launched on Kickstarter today] (https://www.kickstarter.com/projects/claviska/particle-a-fresh-take-on-blogging). I'd love to hear your thoughts on the project.

Also, are there any plans to use [semver](http://semver.org/) after maybe 1.0?

Lastly, any way to support your efforts with LightnCandy? Donations? Particle sticker? Anything? :)

**Comment by zordius** [comment]
1. Good project! Like to see beautiful open source projects with handlebars! :)

1. The original plan is move to 1.0.0 + semver when I feel lightncandy stable and almost cover all handlebars.js features. Actually the 0.89 introduce big fundation changes into lightncandy and covers almost every features in handlebars.js , and 0.9x are for bug fixes.....If we do not get many bugs in 1 months and I can complete the better documentation here ( https://github.com/zordius/HandlebarsCookbook ) , then we can move to 1.0.0 + semver .

1. Thanks a lot! So far I feel good for just watching the number of :star increasing and other projects start to using handlebars/lightncandy . If you wanna support you may twitter or blog about lightncandy . Have a nice day!

**Comment by claviska** [comment]
Beautiful. Thanks for the quick response. Will do, and if you change your mind about # 3 then don't hesitate to let me know.

**Comment by claviska** [comment]
@zordius: Quick update to let you know:

1. "Particle" is now "Postleaf"
2. Postleaf launched today, free and open source: www.postleaf.org

Thought you might be interested. Thanks again for the fastest PHP handlebars engine on the planet! 🙌
