### ISSUE TITLE
Partial block throwing error.

### ISSUE THREAD

**Issue by emphaticsunshine** [zordius/lightncandy#219]
The PHP Code:
-------------
// These are the flags I am using.
```php
 $this->compileFlags = 0
            | LightnCandy::FLAG_BESTPERFORMANCE
            | LightnCandy::FLAG_ERROR_EXCEPTION
            | LightnCandy::FLAG_RUNTIMEPARTIAL
            | LightnCandy::FLAG_SPACECTL
            | LightnCandy::FLAG_SPVARS
            | LightnCandy::FLAG_HANDLEBARS;
```
The Issue:
----------
I am receiving following errors for partial block.

Fatal error: Uncaught exception 'Exception' with message 'Unclosed token {{#}} !!' in /includes/classes/Handlebars/Compiler.php on line 50 Exception: Unclosed token {{#}} !! in /vendor/zordius/lightncandy/src/LightnCandy.php on line 80 Call Stack: 1.4110 3969152 1

I am using latest version - 0.92.

**Comment by claviska** [comment]
Hard to tell without seeing the partial, but sounds like you're missing a closing tag somewhere. For example:

```
{{#if}}
    ...
{{/if}}
```

**Comment by emphaticsunshine** [comment]
I have something like this:

```hbs
{{#> foo}}
   My Content
{{/foo}}
```

**Comment by zordius** [comment]
Sorry for replay late, I tested with template `{{#>foo}}bar{{/foo}}` and compiled with flags you provided, but everything works well.

But, I changed the template to `{{#>foo}}bar` and I got the error: `Unclosed token {{#foo}}` . I think it is wrong and should be `Unclosed token {{#>foo}}` . I will work on this issue and maybe the fix will provide you better error message.

**Comment by zordius** [comment]
Hello @emphaticsunshine , I can not reproduce the error as `Unclosed token {{#}} !!` . Please provide more template detail so I can investigate on this case, thank you for your help! :)
