### ISSUE TITLE
Ignoring the .hbs syntax errors gracefully

### ISSUE THREAD

**Issue by Jiri-Mihal** [zordius/lightncandy#220]
If flags are specified eg. like:
```php
'flags' => \LightnCandy\LightnCandy::FLAG_ADVARNAME
```

And .hbs template contains error eg.:
```hbs
{{ #2 }}
```

Then ::compile fn generates empty result. So just some little mistake in .hbs template prevents to display whole page.

Reproducing the error with:
index.php
```php
$handlebars_options = [
    'flags' => \LightnCandy\LightnCandy::FLAG_ADVARNAME
];
$phpTemplate = \LightnCandy\LightnCandy::compile('Hello {{ #2 }}', $handlebars_options);
$phpTemplate = eval($phpTemplate);
echo $phpTemplate($data);
```
Results to:
`Fatal error: Function name must be a string in index.php on line 6`

But if there aren't flags, the compilation works like expected. Compilation just ignores errors and compiles whole rest of the page. So example below works:
```php
$phpTemplate = \LightnCandy\LightnCandy::compile('Hello {{ #2 }}');
$phpTemplate = eval($phpTemplate);
echo $phpTemplate($data);
```
Is there some possibility to turn on ignoring the .hbs syntax errors gracefully or it's a bug?

**Comment by zordius** [comment]
You may try to use <a href="https://zordius.github.io/HandlebarsCookbook/LC-FLAG_ERROR_LOG.html">FLAG_ERROR_LOG</a> or <a href="https://zordius.github.io/HandlebarsCookbook/LC-FLAG_ERROR_EXCEPTION.html">FLAG_ERROR_EXCEPTION</a> to enable error reporting.

Or, you can use `LightnCandy::getContext()` to receive error right after `LightnCandy::compile()` .

**Comment by Jiri-Mihal** [comment]
Hi and thank you for fast reaction. All the ways you have described just handle errors in different ways, but any of these ways don't allow to compile whole page and ignore errors. I forgot to add result of second example in previous post. It's:
```html
Hello
```
I think this is good behaviour. Template engine just parses correct syntax and ignores wrong syntax without errors. But this behaviour I'm able to achieve just without any 'flags' in options. Unfortunately if I need to use some flag e.g. 'FLAG_ADVARNAME' then I lost described behaviour and I get always some error.

**Comment by zordius** [comment]
Sorry, I misunderstanding the question. So your requirement is wanna skipping the error any way. It's not easy because there are too many types of errors. For your case it should be something about `{{#2}} started without ending {{/2}}` , and it will produce PHP just like an open loop started without ending.

**Comment by zordius** [comment]
But, it is an interesting requirement.

1. For single tag, EX: `{{foo bad"syntax}}` maybe we can skip this token and then skip this token silently.
2. For unpaired open/close tags, EX: `{{#foo}} .... {{/bar}}` maybe we can auto close the `foo` and drop the `bar` . Then the template will be transformed into `{{#foo}} .... {{/foo}}` .

If you like this, it may become a new compile flag and I can work on it. Another issue is, even when LightnCandy can support this, the invalid template still can not survive inside handlebars.js .

**Comment by Jiri-Mihal** [comment]
I tested above mentioned template in handlebars.js and you are totally right. Handlebars.js doesn't allow the syntax errors to be silently ignored. I think it will be better when you don't allow people to make invalid templates. The priority should be handlebars.js back compatibility.

Unfortunately in `FLAG_BESTPERFORMANCE` is possible to parse templates with some syntax errors and it was the point where I started to be confused. So maybe the point is, that `FLAG_BESTPERFORMANCE` should be strict as other flags.

**Comment by zordius** [comment]
`FLAG_BESTPERFORMANCE` should have same behavior when parsing the template, I will checkout the result for `{{#2}}` with different flags to confirm it.

**Comment by Jiri-Mihal** [comment]
Probably the result for  `{{#2}}` always throws error. But the result for `{{ #2 }}` doesn't throw error with `FLAG_BESTPERFORMANCE`.

**Comment by zordius** [comment]
I just tested with handlebars.js and found `{{ #foo }}` is not a valid tag. http://jsfiddle.net/wvmd5ka5/ .
But, it's works well in mustache.js .

In lightncandy , `{{#foo}}` be parsed into `{{#` , `foo` , `}}` and means section.
And, `{{ #foo}}` be parsed into `{{` , `#foo` , `}}` and means a variable lookup. it is valid when there is no LightnCandy::FLAG_ADVARNAME flag.

It's hard to choose a better solution from these possible fix:

1. make `{{ #foo}}` be parsed as section, then it will align with mustache.js but not same with handlebars.js
2. do not change the parsing logic, then it will align with handlebars.js but not same with mustache.js

**Comment by Jiri-Mihal** [comment]
Solution can be to have the possibility to choose between Handlebars and Mustache mode of Lightncandy eg. with some FLAG.

But I think there is still different problem. In Lightncandy is possible to have `{{ #foo }}` without `{{ /foo }}` and it works when you set just `FLAG_BESTPERFORMANCE`. But this doesn't work in Handlebars and Mustache [http://jsfiddle.net/Jiri_Mihal/hn6huemn/](http://jsfiddle.net/Jiri_Mihal/hn6huemn/) So `{{ #foo }}` without `{{ /foo }}` should throw always error, because it's a section without the closing tag.

**Comment by zordius** [comment]
Good point! Will change the parser to allow space between `{{` and `#` .

**Comment by zordius** [comment]
Now lightncandy will allow spacing between `{{` and `#` (or other control characters like `^` , `/` , `>`) , please try current master, thanks.

And, will add more document about the different parsing behavior between handlebars.js and mustache.js .
