### ISSUE TITLE
Helper functions must be placed on their own lines

### ISSUE THREAD

**Issue by claviska** [zordius/lightncandy#221]
When registering helpers, LightnCandy uses the Reflection class to grab the actual function code from the file it's defined in, which is pretty clever. Alas, the [regex that parses closures](https://github.com/zordius/lightncandy/blob/master/src/Exporter.php#L54) is a bit sensitive to the code's format.

For example, if you define your helpers like this, all is well:

```php
$helpers = array(
    'foo' => function($options) {
        return 'foo';
    }
);
```

But if you define your helpers in any of the following (syntactically correct) formats, you'll run into an error on render:

```php
// #Example 1 - doesn't work without line breaks
$helpers = array('foo' => function($options) {
    return 'foo';
});

// Example 2 - doesn't work using shorthand without line breaks
$helpers = ['foo' => function($options) {
    return 'foo';
}];

// Example 3 - doesn't work with one liners
$helpers = array('foo' => function($options) { return 'foo'; });

// Example 4 - doesn't work with multiple functions on one line
$helpers = ['foo' => function($options) { return 'foo'; }, 'bar' => function($options) { return 'bar'; }];
```

The error occurs because the regex isn't stripping everything before "function", resulting in the following compiled code:

```php
use \LightnCandy\SafeString as SafeString;use \LightnCandy\Runtime as LR;return function ($in = null, $options = null) {
    $helpers = array(            'foo' => $helpers = array('foo' => function($options) {
    return 'foo';
});
,
);
// [TRUNCATED FOR CLARITY]
```
There are good use cases where one would want the flexibility of formatting helpers a bit differently. For example, imagine an API where users are able to register their own helpers:

```php
$app->registerHelper('foo', function($options) {
    return 'foo';
});
```
This also fails when passed into LightnCandy because the entire snippet gets copied by the exporter on compile:

```php
use \LightnCandy\SafeString as SafeString;use \LightnCandy\Runtime as LR;return function ($in = null, $options = null) {
    $helpers = array(            'foo' => $app->registerHelper('foo', function($options) {
    return 'foo';
});
,
);
// [TRUNCATED FOR CLARITY]
```
I came up with two possible solutions for this.

## Option 1 (still not perfect)

Replace [this line](https://github.com/zordius/lightncandy/blob/master/src/Exporter.php#L54) with the following:

```php
// Get and trim the function block starting at the first instance of "function" and the last instance of "}"
$func = substr($lines, $spos, $epos - $spos);
$func = substr($func, strpos($func, 'function'));
$func = substr($func, 0, strrpos($func, '}') + 1);
return static::replaceSafeString($context, $func);
```
This is more forgiving and more readable, but it's still flawed because it will return multiple closures if they're on the same line (see Example 4 above).

## Option 2 (better, but needs testing)

Use the tokenizer to parse the function from the code block. I took a stab at this but it's a bit raw. Again, replace [this line](https://github.com/zordius/lightncandy/blob/master/src/Exporter.php#L54) with:

```php
// Grab block that function is in 
$func = substr($lines, $spos, $epos - $spos);

// Tokenize the block
$tokens = token_get_all('<?php ' . $func);

$code = '';
$is_func = false;
$num_func = 0;
$depth = 0;

// Loop through each token
foreach( $tokens as $token ) {
    $append = '';

    if( is_array($token) ) {
        // Are we entering a function?
        if( token_name($token[0]) === 'T_FUNCTION' ) {
            $is_func = true;
            // Only count it if it isn't nested in another function
            if( $depth === 0 ) $num_func++;
            // Is there more than one? If so, the closures are ambiguous and can't be parsed
            if( $num_func > 1 ) {
                throw new \Exception('Cannot parse closure. Make sure functions are defined on their own lines.');
            }
        }

        $append .= $token[1];
    } else {
        // Do nothing if we're not inside a function
        if( !$is_func ) continue;

        // Keep track of brace depth
        if( $token === '{' ) $depth++;
        if( $token === '}' ) {
            $depth--;
            // The function's closing brace occurs when we reach zero again
            if( $depth === 0 ) {
                $is_func = false;
                $code .= '}';
            }
        }

        $append .= $token;
    }

    // Only append the code if we're inside a function
    if( $is_func ) $code .= $append;
}

return static::replaceSafeString($context, $code);
```
Note the exception if more than one closure is found. This is necessary because it's not possible to tell which function is the desired one when multiple functions occur on the same line.

@zordius: I didn't submit a PR because I want your opinion first. Option 2 is a more "proper" approach but there might be a hit on speed. Option 1 will be fast, but doesn't check for multiple closures. What are your thoughts on this?

**Comment by zordius** [comment]
Option 1 is good enough, for example 4. I think it is not good coding style and should be prevented. Maybe we can adopt Option 1 and document more for example 4.

Option 2 is depends on `{` and `}` and may be buggy when the code contains a string with `{` EX: `" test { "` . More complex cases need to be handled (`"` ,`'` then `\` even `/*` , it will be a nightmare).

**Comment by jayS-de** [comment]
Option 2 can be improved using T_CURLY_OPEN. And there should be no problems with strings and comments as you are using the tokenizer. Btw when the runtime is php7 it could be improved by retrieving the AST.

**Comment by jayS-de** [comment]
Another Option would be to try the php-parser by nikic. https://github.com/nikic/PHP-Parser

**Comment by claviska** [comment]
Agree on not formatting code that way, but it would be useful in edge cases where compressed code gets passed in. Not critical but a nice-to-have, so it's worth mentioning.

@jayS-de That was a quick stab at using the tokenizer — I've never played with it before and took some inspiration from [this library](https://github.com/jeremeamia/FunctionParser/blob/master/src/FunctionParser.php#L250) to get it functional.

@zordius Would you prefer option 1 or simply reworking the regex to support some of the additional test cases?

**Comment by zordius** [comment]
Ya in short term refine the regexp can resolve most cases but can not resolve one-line-code. After the quick fix we can still search for other stable + lightweight solutions.

**Comment by claviska** [comment]
Option 1 (string functions) seem to pass all the test cases I'm throwing at it: take everything between the first instance of "function" and the last instance of "}" which is pretty much what the regex is intended to do. It even "passes" example 4 except it lets the second function leak through. (This could be mentioned as a caveat in the docs.)

@zordius Do you want me to PR option 1?

Anyone care to throw some tests at it beforehand?

**Comment by zordius** [comment]
I just add some test cases and refine the regexp, it seems passed all line changed cases.

Old RegExp: get function from `(` and ended at first `}` , maybe followed `,` or `;` , then line change.
New RegExp: get function from `(` and ended at last `}` , drop any other string.

It's not a perfect solution but prevent external dependency. Developers still can extend `\LightnCandy\Exporter` then override the `closure()` function with other PHP parsers/tokenizers.

**Comment by claviska** [comment]
Beautiful. I prefer this approach over adding a heavy dependency. In most cases, a simple grab will suffice. In the rare case where helpers may be passed in compressed (or for some reason) on one line, extending the class with a tokenized approach is definitely acceptable. 👍
