### ISSUE TITLE
Is render Method deprecated?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [zordius/lightncandy#226]
The PHP Code:
-------------

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
put template with issues here...
VAREND;

// Helpers:
$helpers = array(
  'foo' => function () {
    return 'Hello World';
  },
);

// Partials:
$partials = array(
    'bar' => 'Yes, partial',
);

$php = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS,
  'helpers' => $helpers,
  'partials' => $partials,
));

echo "Generated PHP Code:\n$php\n";

// Input Data:
$data = array(
  'qoo' => 'moo'
);

$render = LightnCandy::prepare($php);
echo "Result:\n" . $render($data);
```

The Issue:
----------

When I copy the above code, my IDE shows `render` as *Deprecated*. What was it deprecated in favor of?

**Comment by jayS-de** [comment]
See README from [v0.90](https://github.com/zordius/lightncandy/tree/v0.90). In newer versions the example with the deprecated function has been removed.

```php
// Step 2A. (Usage 1) use LightnCandy::prepare to get rendering function
//   DEPRECATED , it may require PHP setting allow_url_fopen=1 ,
//   and allow_url_fopen=1 is not secure .
//   When allow_url_fopen = 0, prepare() will create tmp file then include it, 
//   you will need to add your tmp directory into open_basedir.
//   YOU MAY NEED TO CHANGE PHP SETTING BY THIS WAY
$renderer = LightnCandy::prepare($phpStr);


// Step 2B. (Usage 2) Store your render function in a file 
//   You decide your compiled template file path and name, save it.
//   You can load your render function by include() later.
//   RECOMMENDED WAY
file_put_contents($php_inc, $phpStr);
$renderer = include($php_inc);
```

**Comment by zordius** [comment]
The `LightnCandy::prepare()` is deprecated, check here for more document: https://zordius.github.io/HandlebarsCookbook/9000-quickstart.html , thanks!

**Comment by altaraven** [comment]
Very-very strange... And what if I don't want to store those php files? Why not to convert the templates directly to string?
If Heroku will be used as hosting it will be impossible to store files which are not under git. So, this way will not work.
This is a pretty good library but I'm very suprised why templates are converted to php files at all, not text files (e.g. html)

**Comment by jayS-de** [comment]
Because of speed. The parsing of the templates is the most expensive part. And all template engines in the wild known for speed are compiling to plain php and caching the templates.

For heroku would to compile your templates in the build step, so they will be included in the build artifact. Your application then just has to include the compiled file.

For my Symfony [HandlebarsBundle](https://github.com/jayS-de/HandlebarsBundle) I implemented a CacheWarmer which you should normally call in your build step.

**Comment by altaraven** [comment]
Thanks for explanations!
