### ISSUE TITLE
Unable to pass stdObject to template

### ISSUE THREAD

**Issue by lisatassone** [zordius/lightncandy#231]
The PHP Code:
-------------
$data = new stdClass();
$data->products = array();
$product = new stdClass();
$product->productTitle = "Product One";
$product->cost= "Free";
$data->products[] = $product;

This is then passed to the render function.

// The Template:
The template is retrieved from file_get_contents and contains:

<div style="margin:0 auto;">
{{#list products}}
  <div>{{productTitle}}</div>
  <div>{{cost}}</div>
{{/list}}
</div>

// Helpers:
(you can see I am converting it to an array by typecasting but if you remove that it won't work):

"list" => function ($context, $options) {
    $ret = '';
    $data = $options["_this"]->$context;
    $j=count($data);
    for($i=0; $i<$j; $i++) {
	    $ret = $ret . $options["fn"]((array)$data[$i]);
	}
	return $ret;
}

The Issue:
----------

While creating a helper function to iterate over an array of objects, it seems as though unless the object is converted to an array, the template won't pick up that object key should be used to render the value. I could be doing something wrong, so please let me know if that's the case, otherwise I would expect this to be part of the functionality.

**Comment by zordius** [comment]
You may need to apply `LightnCandy::FLAG_PROPERTY ` when you do `LightnCandy::compile()` , please check current document: https://github.com/zordius/lightncandy/tree/cd8d96befa1a31dbd1f6e7e9d86316cd381ed830#compile-options: `FLAG_PROPERTY : support object instance attribute access. You MUST apply this if your data contains object. And, the rendering performance will be worse.`

**Comment by lisatassone** [comment]
Thanks @zordius. That's done it :)
