### ISSUE TITLE
#if/else seems to be broken

### ISSUE THREAD

**Issue by lisatassone** [zordius/lightncandy#232]
If you look at https://zordius.github.io/HandlebarsCookbook/0016-if.html you will see it not working as intended.  I also cannot seem to get it working locally either.

**Comment by zordius** [comment]
Thank you for your reporting! I forget to add <a href="https://zordius.github.io/HandlebarsCookbook/LC-FLAG_ELSE.html">LightnCandy::FLAG_ELSE</a> in the example, I should fix the document.

**Comment by zordius** [comment]
Now these document should be fixed by https://github.com/zordius/HandlebarsCookbook/commit/64474fc10a703874a7723c64db69da56739ebef1 :

* https://zordius.github.io/HandlebarsCookbook/0016-if.html
* https://zordius.github.io/HandlebarsCookbook/0017-unless.html

Please try again, thanks!
