### ISSUE TITLE
#if doesn't work with stringParams flag set

### ISSUE THREAD

**Issue by lisatassone** [zordius/lightncandy#233]
If you use that stringParams flag #if block helper doesn't work.

Flags used to compile with:
LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_STRINGPARAMS | LightnCandy::FLAG_INSTANCE

**Comment by lisatassone** [comment]
Further, one is unable to overload the #if function with a helper which could get around this issue. I am using handlebars client-side and want to ability to use any template the same whether its used by JavaScript or PHP so I don't want to have to call #if something else because the PHP version doesn't work. Any ideas? Sorry to be a pain :P

**Comment by zordius** [comment]
Here is an example for handlebars stringParams behavior: https://jsfiddle.net/gLuwxpqq/ . As I know, `stringParams` means 'pass the param name as string into helper' , so the `#if` helper receives `"foo"` then think it is `true`.

Will check lightncandy behavior later.

**Comment by zordius** [comment]
Another friendly remind: based on https://github.com/wycats/handlebars.js/issues/1151 , future version of handlebars will remove `stringParams` support.

**Comment by zordius** [comment]
Just verified the `stringParams` behavior of lightncandy are same with handlebars.js .

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;
$template = "{{#if foo}}OK{{else}}no{{/if}}";

$php = LightnCandy::compile($template, array(
  "flags" => LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_STRINGPARAMS | LightnCandy::FLAG_INSTANCE
));
$render = LightnCandy::prepare($php);
$data = array(
  "foo" => false
);
echo $render($data);
```

**Output** : `OK`

**Comment by zordius** [comment]
Another issue: overload built-in helpers , will check later.

**Comment by lisatassone** [comment]
Ahh I have found my issue. When initially creating a helper function I added stringParams as I didn't know about flag_instance and didn't remove it. As such it was causing havoc with object instances and helper functions.  I have removed this option now and its working like a charm! Thank you!  Would still be nice to have the option of overloading any default helpers but that's a secondary feature :dancer:  Cheers!

**Comment by zordius** [comment]
I just found a bug causes compile error when try to overload built-in helpers, will fix it later.

**Comment by zordius** [comment]
Now the bug should be fixed, please try again, thanks.

Here is a `#if` overriding example:

```php
require_once('./vendor/autoload.php');
use LightnCandy\LightnCandy;

$template = <<<VAREND
{{#if foo}}OK{{else}}no{{/if}}
VAREND;

$phpStr = LightnCandy::compile($template, array(
    'flags' => LightnCandy::FLAG_HANDLEBARS,
    'helpers' => array(
      'if' => function ($arg1, $options) {
          // will be true anyway
          return $options['fn']();
      }
    )
));
$renderer = LightnCandy::prepare($phpStr);
echo $renderer();
```
