### ISSUE TITLE
Use semantic versioning for 0.x versions

### ISSUE THREAD

**Issue by jayS-de** [zordius/lightncandy#238]
It would be cool if you could use the semantic versioning scheme also for the 0.x versions. SemVer says that for 0.x versions on a breaking change you should increase the minor version and for new features and bug fixes the patch version number. This way it would not be necessary to always update dependents for new version without breaking changes.

**Comment by zordius** [comment]
The original plan is move to 1.0.0 + semver someday, thank you for the suggestion!

**Comment by zordius** [comment]
f289f5ecc42ba4ae029d58fb591fcf3a13301002 <= ok no more 0.9x , we should move to 1.0.0 .

**Comment by zordius** [comment]
1.0.0 released.
