### ISSUE TITLE
Anonymys function in helper dont work

### ISSUE THREAD

**Issue by demil** [zordius/lightncandy#239]
this don't work, it is just displaying white screen of death

$micro->components->add_helper('inc',  function ($args) {
    return intval($args) + 1;
  });

but this works:

$micro->components->add_helper('inc','inc');
function inc($args) {
    return intval($args) + 1;
  }

I don understand.

and in $micro->components object:

public function add_helper($name, $helper)
    {
        $this->helpers[$name] = $helper;
    }

and later in lightncandy:

$options['helpers'] = $this->helpers

And it doesnt even displaying anything.

**Comment by zordius** [comment]
1. not sure which framework you used, maybe the issue is not at lightncandy side.
2. generally speaking the custom helper should be provided **BEFORE** compile.
3. If you can provide sample PHP code of pure lightncandy maybe we can find the issue, thanks.
