### ISSUE TITLE
Escapes (backslash and quadruple curly brackets) do not work

### ISSUE THREAD

**Issue by kafoso** [zordius/lightncandy#246]
# Issue

As per documentation on [http://handlebarsjs.com/expressions.html](http://handlebarsjs.com/expressions.html), two methods of escaping the curly brackets exist:

```
\{{escaped}}
```

and 

```
{{{{raw}}}}
  {{escaped}}
{{{{/raw}}}}
```

None of these methods work correctly in this implementation.

# Reproduction

```php
<?php
use LightnCandy\LightnCandy;

$fileName = "lightncandy_" . (intval(microtime(true)*1000)) . ".php";
$phpStr = LightnCandy::compile("foo \{{var1}} {{{{raw}}}} {{var2}} {{{{/raw}}}} bar");
$filePath = '/tmp/' . $fileName;
file_put_contents($filePath, '<?php ' . $phpStr . '?>');
$renderer = include($filePath);
unlink($filePath);
$variables = [
    'var1' => "borked1",
    'var2' => "borked2",
];
$html = $renderer($variables);

echo $html;
```

The output produced by the above is:

```
foo \borked1 } borked2 } bar
```

- Escape on `var1` is completely disregarded.
- Escape on `var2` produces a strange output with two remnant curly end brackets.

# Expected result
The expected result - when escape rules are followed correctly - is:

```
foo {{var1}}  {{var2}}  bar
```

# Considerations

- When an **odd** number of backslashes exist directly preceeding the Handlebars tag, it should be **escaped**. The remaining number of preceeding backslashes - before the now-replaced value - should be `n-1`.
- When an **even** number of backslashes exist, directly preceeding the Handlebars tag, they cancel each other out, and thus it should **not** be escaped. The remaining number of preceeding backslashes should be `n`.

**Comment by zordius** [comment]
Hello, here is the updated PHP code:

```php
<?php
require('./vendor/autoload.php');

use LightnCandy\LightnCandy;

$fileName = "lightncandy_" . (intval(microtime(true)*1000)) . ".php";

$tmpl = "foo \{{var1}} {{{{raw}}}} {{var2}} {{{{/raw}}}} bar";
echo "The template is : $tmpl\n";
$phpStr = LightnCandy::compile($tmpl, Array(
    'flags' => LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_SLASH | LightnCandy::FLAG_RAWBLOCK
));

$filePath = '/tmp/' . $fileName;
file_put_contents($filePath, '<?php ' . $phpStr . '?>');
$renderer = include($filePath);
unlink($filePath);
$variables = [
    'var1' => "borked1",
    'var2' => "borked2",
];
$html = $renderer($variables);

echo $html;
```

The output is:
```
The template is : foo \{{var1}} {{{{raw}}}} {{var2}} {{{{/raw}}}} bar
foo {{var1}}  bar
```

The output is same with handlebars.js 4.0.6 (jsfiddle: https://jsfiddle.net/nfjyx4tv/ )

You can use extra flags when you `compile()` to enable some or all handlebars features, this design brings flexibility for performance or compatibility. Thanks.

**Comment by zordius** [comment]
Please refer to https://github.com/zordius/lightncandy#compile-options , some document already be moved to https://zordius.github.io/HandlebarsCookbook/ .

**Comment by kafoso** [comment]
Perfect. Thank you.
