### ISSUE TITLE
SafeStrings escaped when passed directly as variables

### ISSUE THREAD

**Issue by hfhchan** [zordius/lightncandy#248]
```php
$template = <<<VAREND
{{string}}
VAREND;

$phpStr = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS
));

// Input Data:
$data = array(
  'string' => new \LightnCandy\SafeString('<b>Hello World</b>');
);

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
```

Actual Result:
```
Result:
&lt;Hello World&gt;
```

Expected Result:
```
Result:
<b>Hello World</b>
```

**Comment by hfhchan** [comment]
For now, my workaround is
```
$phpStr = 'function _htmlentities($str){if ($str instanceOf \LightnCandy\SafeString)return $str;return htmlspecialchars($str,ENT_QUOTES,"UTF-8");}' . $phpStr ;
$phpStr = str_replace('\'.htmlentities((string)', '\'._htmlentities(', $phpStr);
```

**Comment by zordius** [comment]
Checking SafeString on input data may make lightnCandy slower, maybe I will support this with another new compile FLAG option. Will do this later, thank you for your reporting!

**Comment by hfhchan** [comment]
Another thing to note would be if this feature is not fully compatible with
the standalone feature -- the global \LightnCandy\SafeString class needs to
be used instead.

Actually, for the standalone feature on, all helpers need to use the fully
qualified names, or they won't work anymore.

>

**Comment by zordius** [comment]
Yes, the standalone feature will try to replace `\LightnCandy\SafeString` into standalone version, This <a href="https://github.com/zordius/lightncandy/issues/215">issue</a> discuss about this behavior.

**Comment by zordius** [comment]
Update: the original issue should be:

```php
require('./vendor/autoload.php');

use LightnCandy\LightnCandy;

$template = <<<VAREND
{{string}}
VAREND;

$phpStr = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS | LightnCandy::FLAG_STANDALONEPHP
));

// Input Data:
$data = array(
  'string' => new \LightnCandy\SafeString('<b>Hello World</b>')
);

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
```

It's only happened when flag `LightnCandy::FLAG_STANDALONEPHP` is on.

**Comment by zordius** [comment]
Hello, I just update the document for all SafeString use cases here: https://zordius.github.io/HandlebarsCookbook/9003-helperescaping.html#SafeStringandFLAG_STANDALONEPHP

**Comment by zordius** [comment]
more document about `safestring` compile option be added here: https://zordius.github.io/HandlebarsCookbook/9903-lcop-safestring.html (  7ec3dac94445e99ba21dd6f7656d0f21a0dbaff6 changed the behavior of this option)
