### ISSUE TITLE
FLAG_JSLENGTH doesn't work with FLAG_METHOD

### ISSUE THREAD

**Issue by djbingham** [zordius/lightncandy#255]
I've just spent a frustrating couple of hours struggling to get FLAG_JSLENGTH to work, eventually discovering that it doesn't work if FLAG_METHOD is also set. Fortunately, in my case I didn't actually need FLAG_METHOD - I had only set it as I was exploring LightNCandy's capabilities and forgot to remove it. However, it is an undocumented limitation, so I wanted to post it here in case it can be fixed/documented or someone else runs into the same issue.

**Comment by zordius** [comment]
Thank you for the report, will try to fix it or update document later.

**Comment by zordius** [comment]
Now should be fixed in version <a href="https://github.com/zordius/lightncandy/releases/tag/v1.0.3">1.0.3</a>, please try again, thanks.
