### ISSUE TITLE
Raw tag contents are stripped from output

### ISSUE THREAD

**Issue by markkimsal** [zordius/lightncandy#259]
Issue #246 identified an issue where the {{{raw}}} tags do not output what is inside of them.  A reference jsfiddle to compare behavior with official handlebars library, but the official library was not setup correctly.  Handlebars.js requires the developer to add a raw handler.

Compare the behavior with a defined raw handler versus the clearly undefined zoobzoob handler: https://jsfiddle.net/op3vro09/5/

I would expect the following program to output:
```
foo {{var1}} {{var2}} bar
```

The PHP Code: 
-------------
```
<?php
require('./vendor/autoload.php');

use LightnCandy\LightnCandy;

$fileName = "lightncandy_" . (intval(microtime(true)*1000)) . ".php";

$tmpl = "foo \{{var1}} {{{{raw}}}} {{var2}} {{{{/raw}}}} bar";
echo "The template is : $tmpl\n";
$phpStr = LightnCandy::compile($tmpl, Array(
    'flags' => LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_SLASH | LightnCandy::FLAG_RAWBLOCK
));

$filePath = '/tmp/' . $fileName;
file_put_contents($filePath, '<?php ' . $phpStr . '?>');
$renderer = include($filePath);
unlink($filePath);
$variables = [
    'var1' => "borked1",
    'var2' => "borked2",
];
$html = $renderer($variables);

echo $html;
```

http://handlebarsjs.com/block_helpers.html#raw-blocks

**Comment by zordius** [comment]
Thank you for reporting this, I will check this issue later.

**Comment by markkimsal** [comment]
After debugging the generated code, the way to make it work is to pass "raw" as a parameter.  The parameter is interpreted as a flag in Runtime::sec() as the second parameter $v

```
<?php
require('./vendor/autoload.php');
use \LightnCandy\Runtime as LR;
$x= function ($in = null, $options = null) { 
    $helpers = array();
    $partials = array();
    $cx = array(
        'flags' => array(
            'jstrue' => false,
            'jsobj' => false,
            'jslen' => false,
            'spvar' => false,
            'prop' => false,
            'method' => false,
            'lambda' => false,
            'mustlok' => false,
            'mustlam' => false,
            'echo' => false,
            'partnc' => false,
            'knohlp' => false,
            'debug' => isset($options['debug']) ? $options['debug'] : 1,
        ),
        'constants' => array(),
        'helpers' => isset($options['helpers']) ? array_merge($helpers, $options['helpers']) : $helpers,
        'partials' => isset($options['partials']) ? array_merge($partials, $options['partials']) : $partials,
        'scopes' => array(),
        'sp_vars' => isset($options['data']) ? array_merge(array('root' => $in), $options['data']) : array('root' => $in),
        'blparam' => array(),
        'partialid' => 0,
        'runtime' => '\LightnCandy\Runtime',
    );
          
    return 'foo {{var1}} '.LR::sec($cx, ((is_array($in) && isset($in['raw'])) ? $in['raw'] : null), null, $in, false, function($cx, $in) {return ' {{var2}} ';}).' bar {{! }}';
};

$variables = [
'var1' => 'foo',
'var2' =>  bar',
'raw' => true
];
$x($variables);
```

Passing "raw"=>true as a variable makes the compiled code pass True instead of Null to L\Runtime::sec().

Down inside sec() it only calls the callback if "true" is the second parameter.
```
        if ($v === true) {
            return $cb($cx, $in);
        }
```


I'm not sure if the generated code needs fixing or not.  I don't see "rawblock" in the flags anywhere.  Why would the contents of a "raw" block have a toggle not to show at all?  Isn't the default behavior exactly similar to a comment? (i.e. hide everything between start and end tags)

**Comment by markkimsal** [comment]
I would think that the generated code for a rawblock callback would check if $cx['flags']['rawblock'] or something and then the compiled code would look like

```
LR::sec($cx, ((is_array($cx['flags']) && isset($cx['flags']['raw'])) ? $cx['flags']['raw'] : null), null, $in, false, function($cx, $in) {return ' {{var2}} ';})
```

But, I reiterate, why would this be runtime optional?  Wouldn't it be benefition if the behavior of {{{{raw}}}} were standardized?  If you pass LightnCandy::FLAG_RAWBLOCK to the compiler then one predictable code should be ouput, if you do NOT pass LightnCandy::FLAG_RAWBLOCK to the compiler then another string of predictable code should be output.

**Comment by zordius** [comment]
Hello, I just found the difference of https://jsfiddle.net/op3vro09/5/ and your PHP code, here the updated PHP code:

```php
require('./vendor/autoload.php');

use LightnCandy\LightnCandy;

$fileName = "lightncandy_" . (intval(microtime(true)*1000)) . ".php";

$tmpl = "foo \{{var1}} {{{{raw}}}} {{var2}} {{{{/raw}}}} bar";
echo "The template is : $tmpl\n";
$phpStr = LightnCandy::compile($tmpl, Array(
    'helpers' => array(
        // THE MISSING RAW HELPER HERE.....
        'raw' => function ($op) {
            return $op['fn']();
        }
    ),
    'flags' => LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_SLASH | LightnCandy::FLAG_RAWBLOCK
));

$filePath = '/tmp/' . $fileName;
file_put_contents($filePath, '<?php ' . $phpStr . '?>');
$renderer = include($filePath);
unlink($filePath);
$variables = [
    'var1' => "borked1",
    'var2' => "borked2",
];
$html = $renderer($variables);

echo $html;
```

I think the behavior of rawblock is correct.

**Comment by markkimsal** [comment]
So, to enable raw tags we need both FLAG_RAWBLOCK and a custom helper?

Why does the output of just FLAG_RAWBLOCK without a helper generate a LR:sec() that comes very close to working.

Is there any interest in supporting {{{{raw}}}} tags with only the FLAG_RAWBLOCK and skip the custom helper?

**Comment by zordius** [comment]
I tested handlebars.js again, yes, you should use rawblock with custom helper or proper input value.

Please check these:
1. https://jsfiddle.net/op3vro09/6/  No custom helper, no raw block
2. https://jsfiddle.net/op3vro09/7/ raw = true, then raw block can be rendered

I also tested lightncandy, the rawblock behaviors are aligned with handlebars.js.
