### ISSUE TITLE
raw by default

### ISSUE THREAD

**Issue by flip111** [zordius/lightncandy#260]
Is it possible to output all values raw by default? (without the use of rawblock or '{{{') Because i'd like to use handlebars for something else than generating html so i don't need to escape html values.

**Comment by zordius** [comment]
According to handlebars document http://handlebarsjs.com/reference.html , the `noEscape` option is the answer of this issue. And, it's lucky for you that there is also a compatible `FLAG_NOESCAPE` flag in lightncandy, you can use this flag to compile your template. Please check the <a href="https://zordius.github.io/HandlebarsCookbook/LC-FLAG_NOESCAPE.html">document with example</a>, thanks.
