### ISSUE TITLE
Compiler gives undefined offset notices

### ISSUE THREAD

**Issue by flip111** [zordius/lightncandy#261]
error `PHP Notice:  Undefined offset: 1 in ~/project/vendor/zordius/lightncandy/src/Compiler.php on line 532`

commit:
https://github.com/zordius/lightncandy/blob/202f7f191d5c7bc61265b10b61a924dc73d79376/src/Compiler.php#L529

```
#0  LightnCandy\Compiler::section() called at [~/project/vendor/zordius/lightncandy/src/Compiler.php:503]
#1  LightnCandy\Compiler::blockBegin() called at [~/project/vendor/zordius/lightncandy/src/Validator.php:241]
#2  LightnCandy\Validator::operator() called at [~/project/vendor/zordius/lightncandy/src/Compiler.php:340]
#3  LightnCandy\Compiler::compileToken() called at [~/project/vendor/zordius/lightncandy/src/Compiler.php:64]
#4  LightnCandy\Compiler::compileTemplate() called at [~/project/vendor/zordius/lightncandy/src/LightnCandy.php:51]
#5  LightnCandy\LightnCandy::compile() called at [~/project/script.php:37]
```

template
```
{{#each foo as |bar|}}
  {{#each bar.undefined}}
  {{/each}}
{{/each}}
```

data
```php
$data = [
  'foo' => []
];
```

Expected:
1. don't try to do stuff in the inner loop when there is nothing to iterate in the outer loop
2. have proper error handler that give sane error messages about template instead of php notifications from Compiler.php

**Comment by zordius** [comment]
Thank you for reporting this issue, will check on this later.

**Comment by zordius** [comment]
Now the error message should be fixed. I also found another issue about lightncandy deal with `{{ ... as |foo|}}` , will track it in #267 .
