### ISSUE TITLE
PHP Fatal error: Function name must be a string in

### ISSUE THREAD

**Issue by flip111** [zordius/lightncandy#262]
When using helper blocks the PHP Fatal error `Function name must be a string` triggers so often without any explanation of why it happens. It's really easy to create this error so i didn't bother to put a test case with it.

EDIT: ok easy example is if you put `{{if}}{{/if}}` instead of `{{#if}}{{/if}}`

Another example: `{{#myCustomTag}}blabla{{wrongClosingTag}}`. I expect an error here saying that tags don't match.

**Comment by zordius** [comment]
Thank you for reporting this issue, will check on this later.

**Comment by zordius** [comment]
Please check this example:

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
{{#myCustomTag}}blabla{{wrongClosingTag}}
VAREND;

$phpStr = LightnCandy::compile($template, array(
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS
));
```

When you compile with `LightnCandy::FLAG_ERROR_EXCEPTION` or `LightnCandy::FLAG_ERROR_LOG` , you will can proper error messages.

**Comment by flip111** [comment]
Why not make this the default and instead add a flag `FLAG_NO_ERROR_EXCEPTION` ? I close this issue because the solution works

**Comment by zordius** [comment]
Good point, may change the FLAG design in future, thanks for the suggestion.
