### ISSUE TITLE
{{this}} not working in #each-loop

### ISSUE THREAD

**Issue by AlexanderBech** [zordius/lightncandy#272]
The PHP Code:
-------------

$variables = array("options" => array("Option 1", "Option 2", "Option 3"));

The template:
-------------

{{#each options}}
<option value="{{this}}">{{this}}</option>
{{/each}}

The Issue:
----------

{{this}} is not working in a simple #each loop.

**Comment by zordius** [comment]
You may forget to include `FLAG_THIS` when you compile, please check these document: https://zordius.github.io/HandlebarsCookbook/0019-each.html , https://zordius.github.io/HandlebarsCookbook/LC-FLAG_THIS.html , thanks.
