### ISSUE TITLE
Mangled output with extended comments in ancient PHP build from the 13th century

### ISSUE THREAD

**Issue by tje** [zordius/lightncandy#273]
The PHP Code:
-------------

```php
use LightnCandy\LightnCandy;

$tpl = <<<HEREDOC
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{title}}</title>
</head>
<body>
  Above

  {{!-- extended comment --}}

  Below
</body>
</html>
HEREDOC;

$compiled = LightnCandy::compile($tpl);
$renderer = LightnCandy::prepare($compiled);

echo $renderer(array(
  'title' => 'Test'
));
```
Output:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test
  Below
</body>
</html>
```

The Issue:
----------

One of the projects I'm working with runs on PHP 5.3.3, and compiling templates with extended comments in them produces bizarre results. I'm fairly certain this is related to a [bug in PHP](https://bugs.php.net/bug.php?id=53958) that has since been patched. I was able to fix it by modifying `Validator::pushLeft`:

```diff
protected static function pushLeft(&$context) {
    $L = $context['currentToken'][Token::POS_LOTHER] . $context['currentToken'][Token::POS_LSPACE];
    if ($context['currentToken'][Token::POS_OP] === '!') {
-       $appender = function (&$pb) use ($context, $L) {
+       $appender = function (&$pb) use (&$context, $L) {
            $pb .= $L;
        };
        if (count($context['partialblock']) > 0) {
        // ...
```

It seems that `$context` becomes overridden/dereferenced within the method scope after the `$appender` closure is defined. Is there any reason that this closure even needs access to that variable?

This is admittedly a niche and trivial issue, especially considering that it's a problem with decrepit PHP builds from Ye Olden Days™, but I figured I'd at least mention it here. Perhaps I'm not the only developer working on websites for noblemen hailing from the Middle Ages.

**Comment by zordius** [comment]
Ya after the code review I think the `$context` is not required inside the `$appender` scope, will remove it from the `use`. Thank you for the report!

**Comment by zordius** [comment]
It should be fixed in current master, please try again. Another Note: we stop testing on PHP 5.3 after v0.90 (2016-01-04) , please refer to official PHP supported versions: http://php.net/supported-versions.php .....Move to PHP 5.6 will be better now.
