### ISSUE TITLE
Exception when parsing string with embedded parentheses

### ISSUE THREAD

**Issue by MasonM** [zordius/lightncandy#274]
The PHP Code:
-------------

```php
<?php
require('./vendor/autoload.php');

use LightnCandy\LightnCandy;

$template = '{{foo "This is a string (with embedded parens). It is not parsed correctly"}}';
$phpStr = LightnCandy::compile($template, [
    'helpers' => [
        'foo' => function () { return 'foo'; },
    ],
    'flags' => LightnCandy::FLAG_ERROR_EXCEPTION,
]);
$output = eval($phpStr);
echo $output(array());
```

The Issue:
----------

The compiler is throwing an exception when parsing a string argument like `"This is a string (with embedded parens). It is not parsed correctly"`

Running the above code on the master branch fails with `Fatal error: Uncaught exception 'Exception' with message 'Unexpected charactor in 'parens).' ! (should it be 'parens)' ?)'`

It appears the period after the closing ")" is necessary to trigger the exception. It works when the period is removed.

**Comment by zordius** [comment]
Thank you for the report! Will try to fix it later.

**Comment by zordius** [comment]
To use string as params, the <a href="https://zordius.github.io/HandlebarsCookbook/LC-FLAG_ADVARNAME.html">FLAG_ADVARNAME</a> flag is required. The updated sample code works well:

```php
<?php
require('./vendor/autoload.php');

use LightnCandy\LightnCandy;

$template = '{{foo "This is a string (with embedded parens). It is not parsed correctly"}}';
$phpStr = LightnCandy::compile($template, [
    'helpers' => [
        'foo' => function () { return 'foo'; },
    ],
    'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_ADVARNAME,
]);
$output = eval($phpStr);
echo $output(array());
```

Thanks.
