### ISSUE TITLE
Ignore exception

### ISSUE THREAD

**Issue by hakimihamdan88** [zordius/lightncandy#276]
The PHP Code:
-------------

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
{{ }}
{{..}}
VAREND;

$phpStr = LightnCandy::compile($template, array(
'flags' => LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_MUSTACHE
));

echo "Generated PHP Code:\n$phpStr\n";

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
```

The Issue:
----------

how to ignore all exceptions? or any callback? Dont want to display error at clients

**Comment by zordius** [comment]
you may add `LightnCandy::FLAG_ERROR_EXCEPTION` into compile flags, and then try/catch the compile() .

**Comment by hakimihamdan88** [comment]
can I skip the error? so lightncandy will be ignore the typo/unsupported syntax

**Comment by zordius** [comment]
to deal with runtime error, you can just put a `@` before it. for example:

```php
echo "Result:\n" . @$renderer($data);
```

**Comment by hakimihamdan88** [comment]
this will throw an exception

`{{#if foo}}FOO{{else}}BAR{{/if}}`

**Comment by hakimihamdan88** [comment]
```
$template = <<<VAREND
{{ }}

{{ name }}
A{{{foo}}}C

{{..}}
{{ .. }}
VAREND;

$phpStr = LightnCandy::compile($template, array(
        ));
var_dump($phpStr);
```

----------
its return false so no point using @

**Comment by zordius** [comment]
to deal with compile time error, you should add `LightnCandy::FLAG_ERROR_EXCEPTION` to compile() , then try/catch the compile() . If you do not like try / catch practice, you should check $phpStr .

example 1:
```php
try {
  $phpStr = LightnCandy::compile($template, array(
'flags' => LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_MUSTACHE | LightnCandy::FLAG_ERROR_EXCEPTION))
} catch (E) {
  // cancel rendering....
}
```

example 2:
```php
$phpStr = LightnCandy::compile($template, array( .... ))

if (!$phpStr) {
  // cancel rendering....
}

```

**Comment by hakimihamdan88** [comment]
but I dont want to cancel rendering, can I force rendering? To ignore the errors

**Comment by zordius** [comment]
Both lightncandy / handlebars.js try to keep rendering 'no error' , but not for compile time. If a template is not valid, we provide enough message for user to correct the error.

You can try http://tryhandlebarsjs.com/ , edit online. When template error it shows error message, any way the rendering result is empty in this case.

**Comment by hakimihamdan88** [comment]
in [liquid](https://github.com/Shopify/liquid) they lets you specify how strictly you want your templates to be interpreted
```
Liquid::Template.error_mode = :strict # Raises a SyntaxError when invalid syntax is used
Liquid::Template.error_mode = :warn # Adds errors to template.errors but continues as normal
Liquid::Template.error_mode = :lax # The default mode, accepts almost anything.
```
any plan for lightncandy?

**Comment by zordius** [comment]
No. If we just bypass the parsing error and generate code for bad template, in most error case you will get PHP code and it output empty string for you, I think is is meaningless. And, if you catch the compile time error, you can get same result (empty string result) for these error case (generate dummy PHP code)
