### ISSUE TITLE
[question] replace varaibles in string without generating file

### ISSUE THREAD

**Issue by waspinator** [zordius/lightncandy#277]
I'm interested in just replacing `{{variables}}` in a php string with actual php variables, without generating files. For example, something like the following:

    $template = "Welcome {{name}} , You win \${{value}} dollars!!\n";

    echo render_template($template, array('name' => 'John', 'value' => 10000));
    echo render_template(template, array('name' => 'Peter', 'value' => 1000));

Is LightnCandy right for this job? Or is it better to try and use regular expressions find `{{variables}}` and `str_replace` them?

**Comment by zordius** [comment]
Depends, for simple template you can do it by regexp or str_replace.

**Comment by waspinator** [comment]
okay, but is it possible to use LightNCandy in the way I describe? Just compiling a template into a string, without writing to a file? From What I see on the quick start, it doesn't seem like it, but just wanted to ask. Thanks.

https://zordius.github.io/HandlebarsCookbook/9000-quickstart.html

**Comment by waspinator** [comment]
https://github.com/bobthecow/mustache.php

another library works well for this use case

```
<?php
$m = new Mustache_Engine;
echo $m->render('Hello {{planet}}', array('planet' => 'World!')); // "Hello World!"
```
