### ISSUE TITLE
Context switching for non-boolean conditionals in mustache

### ISSUE THREAD

**Issue by mrmarkfrench** [zordius/lightncandy#278]
The PHP Code:
-------------

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
{{# set_to_iterate }}
<p>
  This is an item in the set!
  {{# name_enabled }}
    <span>The item is named {{ name }}!</span>
  {{/ name_enabled }}
{{/ set_to_iterate }}
VAREND;

// Helpers:
$helpers = array();

// Partials:
$partials = array();

$phpStr = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_MUSTACHE,
  'helpers' => $helpers,
  'partials' => $partials,
));

echo "Generated PHP Code:\n$phpStr\n";

// Input Data:
$data = array(
  'set_to_iterate' => array(
    array('name_enabled' => 0, 'name' => 'ItemOne'),
    array('name_enabled' => 1, 'name' => 'ItemTwo'),
    array('name_enabled' => false, 'name' => 'ItemThree'),
    array('name_enabled' => true, 'name' => 'ItemFour'),
  )
);

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
```

The Issue:
----------

When iterating a set in a Mustache template, we should be able to use conditionals to check for the existence/truthiness of elements within each item in the set, and apply conditional template logic based on these values.

However, when using a Mustache conditional (which is the same syntax as a Mustache iterator), it appears that if the value being checked is not of type `bool`, the context shifts inside the conditional, which results in other items (which are siblings of the value checked in the conditional) being out-of-scope when we attempt to render them.

When using the `{{# value }}` syntax, the template should iterate if `value` is `Traversable`, and be evaluated as a conditional otherwise.

Instead, it appears the value is checked against `is_bool` and treated as a conditional only if so, and treated as an iterator in all other cases.

**Comment by zordius** [comment]
Sorry for reply late.

Here is the handlebars.js sample: https://jsfiddle.net/9hvuo9gu/

**Comment by zordius** [comment]
Will fix this for better mustache compatibility.

**Comment by zordius** [comment]
New test cases:
* handlebars 4.0.10: https://jsfiddle.net/a6tn5mej/2/
* mustache 2.3.0: http://jsfiddle.net/Lz6jLt26/3/

**Comment by zordius** [comment]
lightncandy v1.2.0 released and includes this fix, please try it, thanks.
