### ISSUE TITLE
Infinite loop in recursive partial

### ISSUE THREAD

**Issue by JulianMar** [zordius/lightncandy#279]
The PHP Code:
-------------

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
VAREND;

// Helpers:
$helpers = array();

// Partials:
$partials = array();

$phpStr = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS,
  'helpers' => $helpers,
  'partials' => $partials,
));

echo "Generated PHP Code:\n$phpStr\n";

// Input Data:
$data = array(

);

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
```

The Issue:
----------

I am using [fractal](https://github.com/frctl/fractal) to build a pattern library and in my comment.hbs file I am including the `@comment` itself like in this [example](https://jsfiddle.net/adamboduch/5yt6M/). It works with handlebars but I am now trying to get it to work with Lightncandy and dynamic data and I just get this error.

PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /private/var/www/nnp/wordpress-custom/wp-content/plugins/vodl-base/vendor/zordius/lightncandy/src/Runtime.php on line 633

It is running in an infinite loop trying to get `@comment`, I guess. I even increased the maximum function nesting level and it didn't change anything

**Comment by jayS-de** [comment]
Seems you forgot to adjust the example. Could you add a template and a partial with some test data. So it's easier to reproduce the error.

**Comment by zordius** [comment]
If you try to rendering a partial recursively, you should enable <a href="https://zordius.github.io/HandlebarsCookbook/LC-FLAG_RUNTIMEPARTIAL.html"> FLAG_RUNTIMEPARTIAL</a> flag.

**Comment by JulianMar** [comment]
I did try that already and it didn't work, I created a [gist](https://gist.github.com/JulianMar/00ef0468b2a014d37b6189211a512a5a) with all the necessary Code.
It is a Wordpress plugin and the data which is given to the `vodl-comment-section.hbs` is in the `vodl-comment-section.hbs` file.

**Comment by zordius** [comment]
I created a minimal PHP sample and can not find any issue in lightncandy:

```php
<?php

use LightnCandy\LightnCandy;

require __DIR__ . '/vendor/autoload.php';

$template = '{{#each comments}}{{> "comment" comment}}{{/each}}';

$phpStr = LightnCandy::compile(
    $template,
    [
        'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARSJS | LightnCandy::FLAG_RUNTIMEPARTIAL,
        'partials' => array(
            'comment' => '! {{user}}:{{words}}{{#each elements}}~{{> "comment" comment}}{{/each}}
'
        )
    ]
);

$renderer = LightnCandy::prepare($phpStr);

echo $renderer(array(
  'comments' => array(
    array('comment' => array(
      'user' => 'a',
      'words' => 'hahaha',
      'elements' => array(
        array('comment' => array(
          'user' => 'a!',
          'words' => 'hahaha!'
        )),
        array('comment' => array(
          'user' => 'a!!',
          'words' => 'hahaha!!',
          'elements' => array(
            array('comment' => array(
              'user' => 'a!!!',
              'words' => 'hahaha!!!'
            )),
            array('comment' => array(
              'user' => 'b!!!',
              'words' => 'hahaha!!!'
            )),
          )
        ))
      )
    )),
    array('comment' => array(
      'user' => 'ib',
      'words' => 'huhuhu',
      'elements' => array(
      )
    )),
    array('comment' => array(
      'user' => 'acc',
      'words' => 'hohoho',
      'elements' => array(
      )
    )),
  )
));
```

**Comment by JulianMar** [comment]
Thank you, it is no issue in lightncandy. It was my error but Thank you for your help.
