### ISSUE TITLE
PartialResolver does not get called when working with dynamic partials

### ISSUE THREAD

**Issue by Rinux55** [zordius/lightncandy#282]
The PHP Code:
-------------

```
return LightnCandy::prepare(LightnCandy::compile($template, [
	'flags' => LightnCandy::FLAG_NOESCAPE | LightnCandy::FLAG_RUNTIMEPARTIAL | 
                        LightnCandy::FLAG_ADVARNAME | LightnCandy::FLAG_ERROR_EXCEPTION],
        'partialresolver' => function($cx, $name) {
                return $name . 'has been called';
         });


//data
{
    foo: 'bar'
}

//template:

{{lookup . 'foo'}} //-> bar

{{> bar}} //-> 'bar has been called'

{{> (lookup . 'foo')}} //-> nothing :(


```
The Issue:
----------

When trying to resolve a partial by using partialresolver, this works fine by just defining 'bar'. 
When you try to do this with a dynamic partial instead, as seen above with the 'lookup', it does not get called. The lookup itself does resolve the correct value, only in combination with the partial resolver it doesn't work.

**Comment by Rinux55** [comment]
Pardon me! I thought i was on the latest version, but I messed up. I was accidentally running an older version. Concider this closed.

**Comment by Rinux55** [comment]
No wait, messed up again. Sorry. It turns out it gets even weirder. If I explicitely call the partial first, and then use the dynamic resolver, it does work:

```
{{> bar}} // bar has been called
{{> (lookup . 'foo')}} //bar has been called
```

If I only have the dynamic, nothing happens. 

```
{{> (lookup . 'foo')}} //nothing happens
```
This time I double checked, I'm running1.2.0.

**Comment by zordius** [comment]
Partial resolver will only be called when at 'Compile time' , not 'Run time (or rendering time)' .

When you compile the template, you do not know the input data, so you can not know the result of `loopup . 'foo'` ....it's depends on the value of `.` . 

Partial resolver is a callback for you to decide partial content when LightnCandy compile the template, and it will only be called when the 'partial name' is known exactly.

When using dynamic partial, you should provide all 'possible partials' for rendering, here are some examples: https://zordius.github.io/HandlebarsCookbook/0028-dynamicpartial.html
