### ISSUE TITLE
Feature Request: Executable partials

### ISSUE THREAD

**Issue by jasonh-brimar** [zordius/lightncandy#285]
In `LightnCandy::compile`, I noticed the return value is a composed render function made by passing the compiled template through `Compiler::composePHPRender`. This seems to apply the appropriate `use` statements and wrap everything in a returned closure.

I have not been able to find a similar function for partials. In the cookbook ([LightnCandy: Deep Dive Partials > Runtime Partials](https://zordius.github.io/HandlebarsCookbook/9004-partials.html#RuntimePartials)) the code sample suggests prepending `return` to the compiled partial. That did not work for me. I had to write my file with the the following:

```php
'use \LightnCandy\Runtime as LR; use \LightnCandy\SafeString as SafeString; return ' . LightnCandy::compilePartial($templateString) . ';'
```

I think there should be a way to compile a partial that returns a composed partial render closure, similar to how `LightnCandy::compile` handles templates via `Compiler::composePHPRender`.

**Comment by zordius** [comment]
Sorry for the long time waiting, will check on this.

Well, here are some ideas about definition of partial:

1. If you want to make partial executable and you are very sure that all your partial files are valid, I think no one will stop you to pre-compile them into PHP by `LightnCandy::compile()` .
2. Continue from 1, actually I will call these `partials` as `templates`.
3. If you also like to include these partials in other templates, it's good. You just need a way to load these partial files (source template, not pre-compiled PHP), then provide these partials to LightnCandy when you want to compile the `other template` .

I can extend the example in https://zordius.github.io/HandlebarsCookbook/9004-partials.html#RuntimePartials :

```php
//// BEFORE
// It will be better to precompile partials and store them into files,
// prevent to use LightnCandy::prepare() in production environment.
$partials = array(
    'foo' => LightnCandy::prepare('return ' . LightnCandy::compilePartial('Hello')),
    'bar' => LightnCandy::prepare('return ' . LightnCandy::compilePartial('World')),
);

//// AFTER
// use LightnCandy::compilePartial() to compile your partials then save them into 'partials' directory.
$partials = array(
    'foo' => require('./partials/Hello'),
    'bar' => require('./partials/World'),
);

//// Executable partials
// use LightnCandy::compile() to compile your partials,
// then save them into 'standalone-partials' directory
```

My option is: the feature you requested is already done.

**Comment by jasonh-brimar** [comment]
Thanks for the response, @zordius! I understand and agree with your explanation of the differences between templates and partials, but I think I should provide more context to explain why I am looking for partials to be executable the same way templates are.

The application I'm working on uses LightnCandy in the view layer. Every one of the application’s components is compiled to both a template and a partial. This allows any component to be rendered explicitly with PHP (e.g. `View::get('foo')->render($context)`) or as a partial with Handlebars via LightnCandy (e.g. `{{> foo childContext}}`).

I need additional functionality to execute whenever a template or partial executes. To accomplish this, I supply wrapper anonymous functions to LightnCandy's `partials` option with the same signature as the partial functions themselves but with the additional functionality.

Therein lies the problem: attempting to invoke the partial generated by LightnCandy without including the necessary `use` statements causes this strategy to fail.

Below is a simplified illustration of what I’m trying to explain:

**foo.hbs**

```hbs
<div>Foo says "{{foo}}"</div>
```

**bar.hbs**

```hbs
<div>Bar says "{{bar}}" and Bar's "foo" property has this to say: <br> {{> foo foo}}</div>
```

**index.php**

```php
<?php

// A simple static class to catch contexts rendered as templates or partials.
class ContextCatcher
{
    public static $caught = [];
    public static function catch($context)
    {
        self::$caught[] = $context;
    }
    public static function empty()
    {
        self::$caught = [];
    }
}

// Wrap a LightnCandy template function to add context-catching functionality.
function wrapTemplate($lightnCandyFunction)
{
    return (
        function ($renderContext, $options) use ($lightnCandyFunction)
        {
            ContextCatcher::catch($renderContext);
            return $lightnCandyFunction($renderContext, $options);
        }
    );
}

// Wrap a LightnCandy partial function to add context-catching functionality.
function wrapPartial($lightnCandyFunction)
{
    return (
        function ($lightnCandyRenderContext, $renderContext, $indentationContext) use ($lightnCandyFunction)
        {
            ContextCatcher::catch($renderContext);
            return $lightnCandyFunction($lightnCandyRenderContext, $renderContext, $indentationContext);
        }
    );
}

// Define LightnCandy compile options. Partials will be supplied at render time.
$compileOptions = [
    'flags' => (
        LightnCandy\LightnCandy::FLAG_HANDLEBARSJS_FULL |
        LightnCandy\LightnCandy::FLAG_ERROR_SKIPPARTIAL |
        LightnCandy\LightnCandy::FLAG_ERROR_EXCEPTION
    )
];

// Create template and partial from foo.hbs.
$fooFileContents = file_get_contents('foo.hbs');
$fooTemplate = wrapTemplate(eval(LightnCandy\LightnCandy::compile($fooFileContents, $compileOptions)));
$fooPartial = wrapPartial(eval('use \LightnCandy\Runtime as LR; use \LightnCandy\SafeString as SafeString; return ' . LightnCandy\LightnCandy::compilePartial($fooFileContents, $compileOptions) . ';'));

// Create template and partial from bar.hbs.
$barFileContents = file_get_contents('bar.hbs');
$barTemplate = wrapTemplate(eval(LightnCandy\LightnCandy::compile($barFileContents, $compileOptions)));
$barPartial = wrapPartial(eval('use \LightnCandy\Runtime as LR; use \LightnCandy\SafeString as SafeString; return ' . LightnCandy\LightnCandy::compilePartial($barFileContents, $compileOptions) . ';'));

// Define LightnCandy render options.
$renderOptions = [
    'partials' => [
        'foo' => $fooPartial,
        'bar' => $barPartial
    ]
];

// Create rendering contexts. Note that the bar context has the foo context as a child for use in a partial.
$fooContext = [ 'foo' => 'foo' ];
$barContext = [ 'foo' => $fooContext, 'bar' => 'bar'];

// Execute the foo template.
$fooTemplate($fooContext, $renderOptions);

// Display the number of contexts rendered as a template or partial. Based on the code above, this should display "1".
echo count(ContextCatcher::$caught);

// Empty the context catcher for a new template execution.
ContextCatcher::empty();

// Execute the bar template.
$barTemplate($barContext, $renderOptions);

// Display the number of contexts rendered as a template or partial. Based on the code above, this should display "2".
echo count(ContextCatcher::$caught);
```

The functionality added in my application’s versions of `wrapPartial` and `wrapTemplate` is much more complicated than what is illustrated here and those functions thus require additional parameters, which is why simply subclassing LightnCandy’s runtime may not be an option.

To be clear, the example illustrated above functions properly; this isn’t a bug. However, I do think that LightnCandy should offer functionality to internally accomplish what I am doing externally with `'use \LightnCandy\Runtime as LR; use \LightnCandy\SafeString as SafeString; return ' . LightnCandy\LightnCandy::compilePartial($barFileContents, $compileOptions) . ';'`. I belive this is important because the way I have it implemented now makes my external code delicate to changes in my LightnCandy dependency’s internal partial compliation functionality.

**Comment by zordius** [comment]
Sorry for the late reply. Here are some questions:

1. Can you change the `eval()` (the runtime compiling) design to `include()` (the pre-compiling) design? It will be better performance.
2. If the answer of 1 is yes, then the second question: we may need to include all partials before we compile or render a template. Do you prefer to include all partials in different partial files, or include all partials from one file?
3. If the answer of 2 is 'use 1 file for all partials', then here is an option to precompile all your partials: output **one** PHP file for all partials, it should be something like this:
```php
<?php
use \LightnCandy\Runtime as LR;
use \LightnCandy\SafeString as SafeString;

$all_partials = array(
  'foo' => $partial_php_code_for_foo,
  'bar' => $partial_php_code_for_bar,
  ...
);
```

And here is code to precompile all partials into one PHP file:
```php
$output = '<?php use \LightnCandy\Runtime as LR;use \LightnCandy\SafeString as SafeString;$all_partials = array(';
foreach($partials as $partial => $name) {
  $output .= "  '$name' => " . LightnCandy\LightnCandy::compilePartial($partial, $compileOptions) . ",\n",
}
$output .= ");";
file_put_contents('all_partials.inc', $output);
```

As you can see, in this use case we will append different code before or after partial code, that's why we do not include `use` , `return` or `;` in the compiled partial code, then developers get freedom to compose their partial code.

**Comment by jasonh-brimar** [comment]
Hi again @zordius, and apologies for my slow response.

I am doing something similar to what you describe above, but I have intermediate `View` objects which wrap the template and partial functions LightnCandy gives me, and attaches additional meta information about each view to deeply integrate the view layer with the other parts of my framework. Because serialization and caching are implemented for performance reasons, I need to be able to lazy-load / `eval` the individual template and partial functions after the `View` objects themselves have been deserialized.

Your description above explains perfectly why `compilePartial` works the way it does. I can see now why forcing the addition of `use`, `return`, and `;` would limit the flexibility of how developers can use partials in their application.

My two cents: I would get value from functionality which applies the `use`, `return`, and `;`, but I acknowledge that such a function should not replace or change the existing `compilePartial` function by default. I suspect there are others who would find functionality like this useful, too. For your consideration, I propose a new `FLAG_COMPOSEDPARTIALS` flag, a new `Compiler::composePHPPartialRender` method, and a conditional branch in `compilePartial` tied to the new flag:

```php
/**
 * Compile handlebars partial into PHP function code.
 *
 * @param string $template handlebars template string
 * @param array<string,array|string|integer> $options LightnCandy compile time and run time options, default is array('flags' => LightnCandy::FLAG_BESTPERFORMANCE)
 *
 * @return string|false Compiled PHP code when successed. If error happened and compile failed, return false.
 *
 * @expect false when input '{{"}}', array('flags' => LightnCandy::FLAG_HANDLEBARS)
 */
public static function compilePartial($template, $options = array('flags' => self::FLAG_BESTPERFORMANCE)) {
    $context = Context::create($options);
    if (static::handleError($context)) {
        return false;
    }
    $code = Partial::compile($context, SafeString::escapeTemplate($template));
    static::$lastParsed = Compiler::$lastParsed;
    // return false when fatal error
    if (static::handleError($context)) {
        return false;
    }
    if ($context['flags']['composedpartials']) {
        $code = Compiler::composePHPPartialRender($context, $code);
    }
    return $code;
}
```
