### ISSUE TITLE
Whitespace control

### ISSUE THREAD

**Issue by rkyoku** [zordius/lightncandy#289]
It would be great to add support for whitespace control:
http://handlebarsjs.com/expressions.html#whitespace-control

I added the tilde, and the template did compile without error, but the whitespaces were not removed.

```
{{#> layout ~}}
<span>test1</span>
<span>test2</span>
{{/layout}}
```

Produces:
```
'.$sp.'<span>test1</span>
'.$sp.'<span>test2</span>
```

Expected result:
```
'.$sp.'<span>test1</span><span>test2</span>
```

**Comment by zordius** [comment]
Sorry for the long time waiting, will check on this.

**Comment by zordius** [comment]
LightnCandy already support space control feature, I will add more document about this. When confirm this issue I found another stand alone tag detection bug about partial block, it's been fixed in current master branch and the behavior of LightnCandy is aligned with handlebars.js 4.0.11 now.

**Comment by zordius** [comment]
I add more document about whitespace control here: https://zordius.github.io/HandlebarsCookbook/0031-whitespace-control.html

**Comment by rkyoku** [comment]
Until then I had modified the output and removed the unwanted `$sp` parts.

But I'm glad to know the feature already exists! Now I can dump my dirty fix ^^

Thanks for the updated documentation!!

Cheers,
