### ISSUE TITLE
@partial-block causes nesting error

### ISSUE THREAD

**Issue by Konmedia** [zordius/lightncandy#291]
The PHP Code:
-------------

```php
require('./vendor/autoload.php');

// Partials
$table = "<div id='table'>{{> @partial-block }}</div>";
$tr = "<div id='tr'>{{> @partial-block }}</div>";
$td = "<div id='td'>{{> @partial-block }}</div>";

// Partial with issue
$test = "
  {{#> table }}
    TABLE<br>
    
    {{#> tr }}
      TR<br>
      
      {{#> td }}
        TD<br>
        
        {{> @partial-block }}
        
      {{/td}}
      
    {{/tr}}
    
  {{/table}}
";

// Template
$template = "{{#> test }}<b>This is my test!</b>{{/test}}";

// Compile
$result = \LightnCandy\LightnCandy::compile(
  $template,
  array(
    "partials" => array(
      "table" => $table,
      "tr"    => $tr,
      "td"    => $td,
      "test"  => $test
    ),
    "flags"    => 0
      + LightnCandy\LightnCandy::FLAG_BESTPERFORMANCE
      + LightnCandy\LightnCandy::FLAG_PROPERTY
      + LightnCandy\LightnCandy::FLAG_METHOD
      + LightnCandy\LightnCandy::FLAG_STANDALONEPHP
      + LightnCandy\LightnCandy::FLAG_HANDLEBARS
      + LightnCandy\LightnCandy::FLAG_ERROR_EXCEPTION
      + LightnCandy\LightnCandy::FLAG_RUNTIMEPARTIAL
      + LightnCandy\LightnCandy::FLAG_EXTHELPER
      + LightnCandy\LightnCandy::FLAG_PARTIALNEWCONTEXT
  )
);

$render = \LightnCandy\LightnCandy::prepare($result);
echo $render(array()); // Fatal error: Maximum function nesting level of '1000' reached, aborting!

```

The Issue:
----------

Using @partial-block to nest templates causes nesting error. Please see the code above.
The above code has been stripped from our framework.

Are we doing something wrong or is a potential bug?

Thank you!

**Comment by zordius** [comment]
Sorry for the long time waiting, will check on this.

**Comment by zordius** [comment]
I created a jsfiddle to verify your use case here: http://jsfiddle.net/4Lkmnru6/21/ , your template is not valid. I think the rule is: "Do not use {{> @partial-block }} inside a partial-block" , and "Use {{> @partial-block}} inside a partial only"

In lightncandy side I will improve the compiler to generate error for this case.

**Comment by zordius** [comment]
Sorry I just did more tests, this should be treat as a 'run time error' . Here is the insight:

1. render the `{{#> table }} .... {{/table}}` : put `TABLE<br> .... </tr>` into partial-block stack, looking for `table` partial.
2. `table` partial found, render it: `<div id='table'>{{> @partial-block }}</div>`
3. when rendering `table` partial we see `{{> @partial-block }}` ,  resolve the partial name `@partial-block` .
4. got `TABLE<br> .... </tr>` from partial-block stack, `@partial-block` resolved, render the partial.
5. clear the partial-block stack, render `TABLE<br> .... </tr>` 
6. render the `<#> tr> ... </tr>` partial block, , put `TR<br> ... </td>` into partial-block stack, looking for `tr` partial.
7. `tr` partial found, render it: `<div id='tr'>{{> @partial-block }}</div>`
8. when rendering `tr` partial we see `{{> @partial-block }}` ,  resolve the partial name `@partial-block` .
9. got `TR<br> ... </td>` from partial-block stack, `@partial-block` resolved, render the partial.
10. clear the partial-block stack, render `TR<br> ... </td>`
11. render the `<#> td> ... </td>` partial block, , put `TD<br>{{> @partial-block }}` into partial-block stack, looking for `td` partial.
12. `td` partial found, render it: `<div id='td'>{{> @partial-block }}</div>`
13. when rendering `td` partial we see `{{> @partial-block }}` ,  resolve the partial name `@partial-block` .
14. got `<div id='td'>{{> @partial-block }}</div>` from partial-block stack, `@partial-block` resolved, render the partial.
15. clear the partial-block stack, render `<div id='td'>{{> @partial-block }}</div>`
16. when rendering `@partial-block` partial we see `{{> @partial-block }}` ,  resolve the partial name `@partial-block` .
17. partial-block stack is empty, so we can not render the `@partial-block` partial. (handlebars.js throw `The partial @partial-block could not be found` in this step)

I will correct lightncandy behavior by this way:
* Clear partial-block stack when a `@partial-block` partial rendering.
* Add error message when a partial is not found.

**Comment by zordius** [comment]
Here is the new sample code:

```php
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
{{#> testPartial}}
  {{#> innerPartial}}
   {{> @partial-block}}
  {{/innerPartial}}
{{/testPartial}}
VAREND;

// Partials:
$partials = array(
  'testPartial' => 'testPartial => {{> @partial-block}} <=',
  'innerPartial' => 'innerPartial -> {{> @partial-block}} <-',
);

$phpStr = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_HANDLEBARS | LightnCandy::FLAG_RUNTIMEPARTIAL | LightnCandy::FLAG_ERROR_EXCEPTION,
  'partials' => $partials,
));

echo "Generated PHP Code:\n$phpStr\n\n";

// Input Data:
$data = array(
);

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
```

The stderr will be (version dev-master):
```
Can not find partial named as '@partial-block' !!
```
