### ISSUE TITLE
Exceptions thrown in helpers being caught and ignored/rethrown

### ISSUE THREAD

**Issue by Quew8** [zordius/lightncandy#300]
The Issue:
----------
If a custom helper function throws an exception then the lightncandy runtime catches it ([here](https://github.com/zordius/lightncandy/blob/0301a34501819af7f04adbed524b3fdc9061d8fe/src/Runtime.php#L679)) and sends it to be either ignored, logged or rethrown. I suggest this is undesirable behaviour on a couple of levels:

- Unless actively passing debug flags to the renderer, exceptions are silently ignored. This might be desirable in some situations but I do not believe it should be the default.
- When exceptions are caught, almost all of the debugging data is thrown away except for the message - no stack trace, no class of exception and no extra information. This makes the debugging flags needlessly limiting for actually doing debugging.
- This behaviour does not change how templates are rendered at all. If there is an exception thrown the template still fails to render - it is paramount to providing a default value whilst preventing users from performing their own error handling.

As such my suggestion is to do away with the exception catching altogether or at the least change the handling so that a new exception is thrown with the original exception chained on ([here](https://github.com/zordius/lightncandy/blob/0301a34501819af7f04adbed524b3fdc9061d8fe/src/Runtime.php#L110)).

**Comment by zordius** [comment]
Thank you for your reporting! Will think about this and maybe make an enhancement on this.

**Comment by zordius** [comment]
in commit 7b36709174c92e22e3b4187a36e45965c69b9c3a original custom helper error call stack should been kept, please try current master or 1.2.5-dev, thanks!
