### ISSUE TITLE
Value "0" not rendered if inside conditional

### ISSUE THREAD

**Issue by Krinkle** [zordius/lightncandy#305]
The PHP Code:
-------------

```php
require './vendor/autoload.php' ;
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
* Value: <b>{{{value}}}</b>.
* Conditional: {{#value}}<b>Yes</b>{{/value}}.
* Conditional value: {{#value}}<b>{{value}}</b>{{/value}}.
VAREND;

$phpStr = LightnCandy::compile($template, array(
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_MUSTACHELOOKUP,
));

echo "Generated PHP Code:\n$phpStr\n";

// Input Data:
$data = array(
  'foo' => '0'
);

// Render:
file_put_contents('render.php', '<?php ' . $phpStr . '?>');
$renderer = require './render.php';
echo "Result:\n" . $renderer($data);
```
```php
<?php
use \LightnCandy\SafeString as SafeString;use \LightnCandy\Runtime as LR;return function ($in = null, $options = null) {
    $helpers = array();
    $partials = array();
    $cx = array(
        'flags' => array(
            'jstrue' => false,
            'jsobj' => false,
            'jslen' => false,
            'spvar' => false,
            'prop' => false,
            'method' => false,
            'lambda' => false,
            'mustlok' => true,
            'mustlam' => false,
            'mustsec' => false,
            'echo' => false,
            'partnc' => false,
            'knohlp' => false,
            'debug' => isset($options['debug']) ? $options['debug'] : 1,
        ),
        'constants' => array(),
        'helpers' => isset($options['helpers']) ? array_merge($helpers, $options['helpers']) : $helpers,
        'partials' => isset($options['partials']) ? array_merge($partials, $options['partials']) : $partials,
        'scopes' => array(),
        'sp_vars' => isset($options['data']) ? array_merge(array('root' => $in), $options['data']) : array('root' => $in),
        'blparam' => array(),
        'partialid' => 0,
        'runtime' => '\LightnCandy\Runtime',
    );
    
    $inary=is_array($in);
    return '* Value: <b>'.LR::v($cx, $in, isset($in) ? $in : null, array('foo')).'</b>.
* Conditional: '.LR::sec($cx, LR::v($cx, $in, isset($in) ? $in : null, array('foo')), null, $in, false, function($cx, $in) {$inary=is_array($in);return '<b>Yes</b>';}).'.
* Conditional value: '.LR::sec($cx, LR::v($cx, $in, isset($in) ? $in : null, array('foo')), null, $in, false, function($cx, $in) {$inary=is_array($in);return '<b>'.htmlspecialchars((string)LR::v($cx, $in, isset($in) ? $in : null, array('foo')), ENT_QUOTES, 'UTF-8').'</b>';}).'.';
};
```

The Result:
----------

```html
* Value: <b>0</b>.
* Conditional: <b>Yes</b>.
* Conditional value: <b></b>.
```

The Issue:
----------

The string value `0` (zero) is not printed when used inside a conditional.

This is unexpected because:
* The value is printed correctly when used plainly.
* The value is considered "truthy" when used as conditional.

And yet, the value is not printed within the conditional. This is reproducible on v0.23, v1.2.2 and current dev-master (0301a34).

Downstream issue:
* https://phabricator.wikimedia.org/T219864

**Comment by zordius** [comment]
Thank you for your report! I will creating a jsFiddle first to confirm the handlebars.js behavior.

**Comment by zordius** [comment]
Please refer to these jsfiddle results:

handlebars.js 4.1.1: https://jsfiddle.net/0rec6d2f/
mustache.js 3.0.1: http://jsfiddle.net/4nLockuy/

Here are some mustache <=> handlebars difference, you can refer to these document:

About block:
https://zordius.github.io/HandlebarsCookbook/0008-block.html#BlockforFalse  (search for 'Only mustache.js will think 0 as false')

About #if:
https://zordius.github.io/HandlebarsCookbook/0016-if.html (search for '0 means false')

If you like to follow mustache, the `FLAG_MUSTACHE` is good, you may also check the document https://github.com/zordius/lightncandy , search 'Mustache Compatibility' for more detail.

If you like to follow handlebars.js, you should use `FLAG_HANDLEBARS` or check the document https://github.com/zordius/lightncandy , search 'Handlebars Compatibility' for more detail.

So far I think current lightncandy followed handlebars.js and mustache spec well (when it's compiled with correct flags)

Now I flag this as invalid, welcome to provide more feedback, or re-open this when you still found some issue, thanks.

**Comment by zordius** [comment]
For reference.

* I believe there is mistake in the issue PHP Code:
```php
// Input Data:
$data = array(
  'foo' => '0'  // should be 'value' => '0'
);
```

Here are updated jsfiddle:
* handlebars.js: https://jsfiddle.net/xL56rpem/1/
* mustache.js: http://jsfiddle.net/h8nsrxb4/

* `FLAG_MUSTACHE` output for the fixed issue PHP Code:
```
Result:
* Value: <b>0</b>.
* Conditional: .
* Conditional value: .
```

* `FLAG_HANDLEBARSJS` output for the fixed issue PHP Code:
```
Result:
* Value: <b>0</b>.
* Conditional: <b>Yes</b>.
* Conditional value: <b></b>.
```


............... Sorry, I just notice you are focus on string `'0'` but not number 0, and current lightncandy is not same as mustache.js actually. If it's right, please re-open this issue, thanks.

**Comment by Krinkle** [comment]
(I cannot reopen the issue.)

**Comment by Krinkle** [comment]
Could you re-open the issue?

**Comment by theodorejb** [comment]
Handlebars 4.7.8 (the latest version) also doesn't render 0 in the conditional:

[Playground link](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22*%20Value%3A%20%3Cb%3E%7B%7B%7Bvalue%7D%7D%7D%3C%2Fb%3E.%5Cn*%20Conditional%3A%20%7B%7B%23value%7D%7D%3Cb%3EYes%3C%2Fb%3E%7B%7B%2Fvalue%7D%7D.%5Cn*%20Conditional%20value%3A%20%7B%7B%23value%7D%7D%3Cb%3E%7B%7Bvalue%7D%7D%3C%2Fb%3E%7B%7B%2Fvalue%7D%7D.%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20value%3A%20'0'%5Cn%7D%5Cn%22%2C%22output%22%3A%22*%20Value%3A%20%3Cb%3E0%3C%2Fb%3E.%5Cn*%20Conditional%3A%20%3Cb%3EYes%3C%2Fb%3E.%5Cn*%20Conditional%20value%3A%20%3Cb%3E%3C%2Fb%3E.%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.8%22%7D)
