### ISSUE TITLE
Turn off evaluating dot notation

### ISSUE THREAD

**Issue by jseparovic1** [zordius/lightncandy#317]
Is it possible to `turn off` dot notation, and just access keys in array?

```php
$template = "{{user.firstname}}"

$data = [
  'user.firstname' => 'Muhamed'
];

$renderer($data);
```

**Comment by jenschude** [comment]
But then you would have to flatten all paths inside your array. And how do you want to define arrays inside your data? This would end in a mess of expanded and partial paths.

**Comment by jseparovic1** [comment]
@jenschude I don't really understand what you wanted to say, but in the meanwhile i found a solution [here](https://zordius.github.io/HandlebarsCookbook/LC-FLAG_ADVARNAME.html).

With this i can use it as following:
```php
$template = "{{[user.firstname]}}"

$data = [
  'user.firstname' => 'Muhamed'
];

echo $renderer($data); // outputs "Muhamed".
```

**Comment by jenschude** [comment]
Think about following:

template:
```
First name: {{user.firstName}}
Last name: {{user.lastName}}
Comments: 
{{#each user.comments}}
  {{text}}
{{/each}}

```

When you would disable dot notation the resulting array would look like this:

```php
$data = [
 "user.firstName" => "Foo",
 "user.lastName" => "Foo",
 "user.comments" => [
    ["text" => "Lorem ipsum"]
 ]
]
```

And as you can see in the template as well in the data array you mix relativ and absolut paths. Which makes it harder to read and write it.
