### ISSUE TITLE
Mustache blocks pragma support

### ISSUE THREAD

**Issue by Arantor** [zordius/lightncandy#319]
One of the features Mustache has that I can’t see in the docs for Lightncandy is their block support (which isn’t the same as the HB term)

Docs: https://github.com/bobthecow/mustache.php/wiki/BLOCKS-pragma

It gives some very useful capabilities for some content to be able to specify a container to be imported in (like a partial) and to insert values and markup into that container before being included into the wider rendering.

Is it just a case that I’m not reading the docs correctly or that it doesn’t support it? I did briefly try to understand the source code but feel like this is something that will need much more time and energy to get my head around.

**Comment by zordius** [comment]
I read the comments in https://github.com/mustache/spec/pull/75 , because it's not merged into spec so I will not support it, sorry.

**Comment by Arantor** [comment]
No worries, I misunderstood which spec was core Mustache.
