### ISSUE TITLE
PHP7.4 rc2 incompatible implode

### ISSUE THREAD

**Issue by storeman** [zordius/lightncandy#320]
The Issue:
----------

I get an error about invalid argument order in PHP 7.2RC2

    Compiler.php:306
    Was: implode($L, ',')
    Fix: implode(',', $L)

    Compiler.php:552
    Was: implode($bp, ' ')
    Fix: implode(' ', $bp)

I wanted to make a pull request, but testing on windows is not supported.

**Comment by zordius** [comment]
thank you for your report! Will check on this issue.

**Comment by zordius** [comment]
confirmed as a bug.

**Comment by zordius** [comment]
This should be fixed in current master, please try version: dev-master , thanks.
