### ISSUE TITLE
New release (with PHP 7.4 support)!

### ISSUE THREAD

**Issue by reedy** [zordius/lightncandy#325]
I'd love a release with https://github.com/zordius/lightncandy/commit/ade2d444c7ce856de174e62fd1aee95dd7bf7760 in so I don't get spammy logs using PHP 7.4 (and I don't have to modify the code myself)

https://github.com/zordius/lightncandy/compare/v1.2.4...master - 34 commits, 7 months as of writing

**Comment by reedy** [comment]
Ok, there's numerous blockers to this...

**Comment by reedy** [comment]
As per #327; #336, #328 and #326 really need to land

**Comment by reedy** [comment]
Hey @zordius,
Thanks for merging most of my other patches.

Any chance we could get traction on the last couple of PR at #336 (to fix the last known PHP 7.4 issue, the fix isn't the best, so better alternatives welcome), then #326 to start testing on PHP 7.4, while also getting build failures to actually flag (#329) for future development?

This then also cleans up and closes #327

Then getting a release of some sort tagged; 8 months and 57 commits have passed (so far) - https://github.com/zordius/lightncandy/compare/v1.2.4...master since the last one. This would help us with the MediaWiki 1.35 release (though, we'll be branching from master soon in preparation for this, and to help us stabilise; we can do backports where necessary), due to be released in June 2020. We already went from lightncandy v0.23 to v1.2.4 in an overdue upgrade in https://github.com/wikimedia/mediawiki/commit/7c4e9f790a48bedc1c314162a5fd2068faae1cb1 but with the prevalence and stable PHP 7.4 release, we don't want to knowingly be including code that may cause logspam for those that are using PHP 7.4. And obviously, we don't want to have to fork just for these couple of smaller fixes.

I know that it's just not going to be the MediaWiki community that would benefit from having them, again due to the prevalence of PHP 7.4 in the wild.


Thanks again

**Comment by kghbln** [comment]
@zordius It will be cool to somehow have progress here. Thanks a lot!

**Comment by zordius** [comment]
Sorry for replying late, will deal with this A.S.A.P, and thanks for a lot of contribution!

**Comment by zordius** [comment]
Now, new version 1.2.5 is released and thanks for contributors!

**Comment by reedy** [comment]
Thanks!

**Comment by kghbln** [comment]
Thank you! Much appreciated!
