### ISSUE TITLE
The problem in PHP8

### ISSUE THREAD

**Issue by mitsh** [zordius/lightncandy#348]
This issue has appeared after upgrading to PHP8.
```
Parse error: syntax error, unexpected token "*" in /tmp/lci_7myMwD on line 2
```

I did a search and found the problem and I made a change in this file;
./src/vendor/lightncandy/Exporter.php
```php
/**
 * Get metadata from ReflectionObject
 *
 * @param object $refobj instance of the ReflectionObject
 *
 * @return array
 */
public static function getMeta($refobj)
{
    $fname = $refobj->getFileName();
    $lines = file_get_contents($fname);
    $file = new \SplFileObject($fname);
    // $file->seek($refobj->getStartLine() - 2);     <-- this is the old one
    $file->seek($refobj->getStartLine() - 1);
    $spos = $file->ftell();
    //     $file->seek($refobj->getEndLine() - 1);   <-- this is the old one
    $file->seek($refobj->getEndLine());
    $epos = $file->ftell();
    unset($file);
    return array(
        'name' => $refobj->getName(),
        'code' => substr($lines, $spos, $epos - $spos)
    );
}
```

Is this a correct way to fix it?

**Comment by VascularEngineer** [comment]
This is also helping for me. I'm also on php 8. Not sure if it is the right way to go, I hope we get some feedback on that.
I had a similar error, mine was 

CRITICAL: Uncaught Exception ParseError: "syntax error, unexpected token ","" at /tmp/lci_Z3NgN8 line 14 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected token \",\" at /tmp/lci_Z3NgN8:14)"}

**Comment by yurikuzn** [comment]
Regarding `syntaxerror, unexpected token ","`. Here's the place that needs to be fixed: https://github.com/zordius/lightncandy/blob/v1.2.5/src/Exporter.php#L65

**Comment by yurikuzn** [comment]
My fix. Not tested enough yet: https://github.com/yurikuzn/lightncandy/commit/207d424c4ced34644663fdc0758c19d5b6974adc

**Comment by danmcadams** [comment]
I actually came across this and ended up doing the same thing you did. The problem is the change isn't backwards compatible.

**Comment by cleoclatskid** [comment]
Just tried out the above fix  yurikuzn@207d424
and it works nicely!
Thanks

**Comment by kohlerdominik** [comment]
@mitsh Can you make a PR from this?

**Comment by kohlerdominik** [comment]
> 
> 
> My fix. Not tested enough yet: [yurikuzn@207d424](https://github.com/yurikuzn/lightncandy/commit/207d424c4ced34644663fdc0758c19d5b6974adc)

Works for me, too. Can you make a PR from this @yurikuzn ?

**Comment by yurikuzn** [comment]
Done: https://github.com/zordius/lightncandy/pull/351

**Comment by mitsh** [comment]
@yurikuzn's approach is more compatible than mine. so, we can close this issue.
